### ISSUE TITLE
KDF SNMP Generation Issue

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#1051]
![image](https://user-images.githubusercontent.com/50221973/97510920-e8d80180-19d9-11eb-99e0-110151baf13b.png)
In the spec, the passwordLength seems to be in "bits" when creating a test session for KDF SNMP.

However, when we put 64 as the minimum. It generates 64 bytes in the vector sets instead of 8 bytes.
And if we put 8 (assuming that should be "bytes" instead of "bit"), we got rejected with an error message,

> Password length must be at least 8 bytes

So, my question is whether 64 minimum is 'byte' or 'bit'.

**Comment by celic** [comment]
PasswordLen is in bytes yes. The specification indicates that it wants bits (both in the description and valid values). Seems like the test case generation expects bytes while the parameter checking expects bits. I'll get this squared away for a future deployment.

**Comment by celic** [comment]
We are going to keep everything in bits, as we use bits for most algorithms. I will update the specification to include a mandatory increment of 8, because only bytes are supported. The code on the back end has been updated so that when you specify 64 bits, the password is actually 64 bits, not 64 bytes.

**Comment by celic** [comment]
Spec updated with 6d3eda8. Code fix is coming in the next demo deployment.
