### ISSUE TITLE
acvp-client version ?

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#106]
Is this even used ?

User Agent: acvp-client/0.3

**Comment by atvassilev** [comment]
I see no use for it but defer to Harold.

**Comment by hbooth** [comment]
I only look at the acvVersion contained in the Json. User Agent is unreliable for a variety of reasons.

**Comment by atvassilev** [comment]
Thinking about it more, at this stage largely because our algorithm testing standards are client-agnostic, there is no need to know specific client attributes that would allow the server to customize the tests for a particular client type. In other words, testing AES is the same regardless if it is used in a mainframe, desktop, router/switch, USB stick, smart card, smart thermostat, etc. 

Our colleagues working on new lightweight crypto standards for IoT are considering possibilities where the testing of some new algorithms may depend on the context in which they are used/implemented, i.e. on the client. So, in the future we may need to identify the type of client, not just the algorithm. One alternative to this may be adding properties to the OE, of course. 

For now, I think we can get rid of acvp-client/v and add a client property when we need it, in a future version of the protocol.

**Comment by atvassilev** [comment]
Resolved with PR#113
