### ISSUE TITLE
Getting 404 not found using links from documentation

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP#1068]
Reproducibility: 100%

Repro case

1. Open ACVP spec at https://usnistgov.github.io/ACVP/
2. Navigate to Supported Algorithms section.
3. Click on any HTML link.

Expected behavior:
Browser navigates to the algorithm ACVP spec

Actual behavior:
Fails with 404 Not Found.

**Comment by Kritner** [comment]
Looks like we're having some trouble with our metanorma build process at the moment, I'll update when I know more

**Comment by jbarnesweb** [comment]
Still not resolved. Are the doc pages being generated at all? Is there a pattern to the URL if they are?

**Comment by Kritner** [comment]
some of them are being generated, but there's no real rhyme or reason to it.  until the issue is resolved, here are the generated documents, since they're all still generating correctly locally, just not via our build process.
[20201118-ACVP-Specification.zip](https://github.com/usnistgov/ACVP/files/5561745/20201118-ACVP-Specification.zip)

**Comment by Kritner** [comment]
Oh, it seems my manual update of our gh-pages branch did actually update the documents at https://usnistgov.github.io/ACVP/, when i initially checked it didn't seem to have worked; maybe I was working with a cached version or something.
