### ISSUE TITLE
KAS-FFC TwoStep with Key Confirmation "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1069]
Hi,

We are getting a "Object reference not set to an instance of an object." as the response to a submission that by all accounts looks correct in non sample mode.

In sample mode we have also observed some interesting behaviour where the VAL tests pass but the AFT tests fail with "MacKey does not match; MacData does not match" even though it is same underlying module code just with key generation.

[non_sample.zip](https://github.com/usnistgov/ACVP/files/5556331/non_sample.zip)
[sample.zip](https://github.com/usnistgov/ACVP/files/5556328/sample.zip)

I have attached the capabilities request, the request vectors, our response and the server response for non sample mode and sample mode.

Would it be possible, in sample mode, to include the private keys in the request for AFT so that it is possible to calculate the same values as supplied in the sample.

MW

**Comment by Kritner** [comment]
I'll have a correction onto demo for the error you received on the non sample today.  Will update this issue when it's up on demo.

Regarding the inclusion of the private keys within the prompt file when a sample vector set, I'm kind of torn.
On the one hand the prompt file is *supposed* to be representative of what the IUTs can expect in a "non sample scenario", but on the other without the private keys, you don't have enough information in order to complete your responses.  The private keys can be grabbed from the expected answers file, but that seems pretty inconvenient; though if they're grabbed from the prompt file that may lead to incorrect assumptions about a "non sample" vector set.

I'll talk about this internally a bit to see if anyone feels strongly one way or the other.

FWIW when I corrected the issue on our end regarding the non sample vector set, your VS passed.

**Comment by Kritner** [comment]
this change is now on demo

**Comment by mwcw** [comment]
> I'll have a correction onto demo for the error you received on the non sample today. Will update this issue when it's up on demo.
> 
> Regarding the inclusion of the private keys within the prompt file when a sample vector set, I'm kind of torn.
> On the one hand the prompt file is _supposed_ to be representative of what the IUTs can expect in a "non sample scenario", but on the other without the private keys, you don't have enough information in order to complete your responses. The private keys can be grabbed from the expected answers file, but that seems pretty inconvenient; though if they're grabbed from the prompt file that may lead to incorrect assumptions about a "non sample" vector set.
> 
> I'll talk about this internally a bit to see if anyone feels strongly one way or the other.
> 
> FWIW when I corrected the issue on our end regarding the non sample vector set, your VS passed.


Thanks for that we have success for both TwoStep and OneStep.

MW

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14)
