### ISSUE TITLE
Algorithm Registration Versioning (revision) and What It Means?

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#1073]
**Protocol Section**
While not specific to any one algorithm or protocol, this question's genesis comes from noticing that the SHA-3 secure hash algorithms have had a revision 2.0 added.

Examples:
https://usnistgov.github.io/ACVP/draft-celi-acvp-sha3.html#section-5-2.5.1

**Protocol Question**
The generic flavour of the question is: what does a change in version actually end up meaning?  Does this indicate a change in the registration payload data?  Does it indicate a change in the types of tests that are generated?  Both?  On top of that, what does a change from `1.0` -> `2.0` indicate versus a change from `1.0`-> `1.1`?  There seems to be bit of inconsistency here.  Recently in the case of RSA, there had been versions added for `FIPS140-2`, `FIPS140-4` and `FIPS140-5`.  In the case of KAS, there is `1.0` as well as `SP800-56Ar3`.

Is it the intention that when an algorithm revision changes, the previous one is deprecated, or are they meant to exist in parallel and continue to be used?

I fired a bunch of questions here.  If this is already documented and explains, feel free to tell me to RTFM.

**Comment by celic** [comment]
Sorry this response got long, quickly. Transparency is my goal here. If we share our logic with everyone, there are less surprises overall.

So when we originally made the revision field, everything was set to 1.0. We realized this had zero context to the actual algorithm and didn't help much overall. So we started making the revisions match the exact version of the algorithm standard the testing is geared towards. 

This is great when, like for FIPS186 multiple revisions are available for testing. But in some cases, multiple revisions could point towards the same version of a standard. In the case of SHA3 1.0 and 2.0, they point to the same standard but offer different ways of registering for that algorithm. The testing within is slightly different because the properties the testing code has access to is different. So we decided a 2.0 was appropriate instead of adding parameters to 1.0. 

**We do not want to add non-optional properties or modify the existing registrations outside of bugfixes.** We want these to be considered "stable". There are some extreme cases of an algorithm used so infrequently that modifications do not affect any existing validations, or validations in progress. When a new revision is introduced, old ones **may** be placed on a "transition schedule" to be deprecated, at which point it is easy to remove access to them on the server. For example, FIPS186-5 is going to be published soon. When it does, `RSA / SigGen / FIPS186-4` will be placed on a transition schedule and after a certain period of time, ACVTS will no longer accept registrations for it. This is not new to the CAVP, but has yet to occur within ACVTS. This will always be communicated up-front to all ACVTS users and labs. 

In the case of the multiple SHA3 revisions, we consider 2.0 to be slightly better than 1.0 because it allows subsets of the old registration to be valid for implementations that have message length requirements. We do not currently have plans to force a transition, but I'm sure you will find all 1.0 registrations are possible in a 2.0 registration, and more. If users are satisfied with this, we may deprecate 1.0 down the road, but as mentioned that will be communicated fully. 

These are good questions, and we have put a lot of thought towards how to maintain this system for the long term. Revisions didn't always exist within ACVP. In this case they allow us to expand functionality while not breaking existing clients.

**Comment by AlexThurston** [comment]
As always, thanks very much for the the thoughtful reply.  I've got a couple of follow-up questions:

> But in some cases, multiple revisions could point towards the same version of a standard.

How or why would vendor or lab know that they want to use version 1.0 or 2.0 in this case?  You mentioned that there is more control with version 2.0 as to what you are registering which might prompt them wanting to use 2.0 to benefit from the additional control, but without having initiated this conversation, how would a lab or vendor know that that is one of the difference?

> In the case of SHA3 1.0 and 2.0, they point to the same standard but offer different ways of registering for that algorithm. The testing within is slightly different because the properties the testing code has access to is different. So we decided a 2.0 was appropriate instead of adding parameters to 1.0.

When you say that testing is slightly different?  Could this have an effect on the vendor's test harness that is feeding the vectors through their IUT?  Specifically, if their harness is expecting a certain type of test but using version 2.0 results in there being different test groups that need to be handled?

**Comment by celic** [comment]
This should all be present in the SHA3 ACVP specification. 

If both revisions are "approved" by the CAVP (e.g. available on the server under `/algorithms`) then a vendor can choose either. The differences are in the specification, but could be made a bit clearer. I'll make some edits so that this is more apparent.

Testing is slightly different in that both will try to grab a number of message lengths that meet certain requirements. For 1.0, the message lengths used are the same every time. The only difference comes in for the `bitOrientedInput` boolean, which really just adds more tests when set to true. The message lengths are centered around the block size of the hash function. This concept doesn't carry over well from SHA2 to SHA3, so the capacity is used instead. This just means there are tests geared towards single blocks, (or single sponge capacities) and multiple blocks (or multiple sponge capacities). When the additional information of the domain `messageLength` is available, we can choose these values more intelligently, rather than using the same exact lengths for every vector set. Two SHA3-2.0 registrations with the same `messageLength` domain will almost always get different message lengths in their prompts. 

Because of this, perhaps saying the testing is different is misleading. The test types are the same. Test harnesses should process the same. From a client perspective, nothing changes past the registration. From a server perspective, the test case selection process is completely different. The differences (or lack of differences) should be pointed out in the SHA3 specification and I'll make those edits.
