### ISSUE TITLE
New module registration in "Initial" state

### ISSUE THREAD

**Issue by davyrouillard** [usnistgov/ACVP#1084]
**Protocol Section**
https://usnistgov.github.io/ACVP/draft-fussell-acvp-spec.html#name-register-a-new-module

**Protocol Question**

Hello,
I have tried to register a new module on the prod server but the status stays stuck at the "initial" status.

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "url": "/acvp/v1/requests/13487",
    "status": "initial"
  }
]
```
In my request, I have reused already existing resources for  the vendorUrl, addressUrl, contactUrls fields.

What I must I do to obtain a approved status ?

**Comment by celic** [comment]
We recommend you email `acvts-prod@nist.gov` with the request ID asking for approval. All Prod requests need manual approval because the content ends up on the NIST website. Human eyes are needed somewhere in the process. If a request item isn't past the `initial` status after an hour or so, an email alerts the reviewer to check.

**Comment by celic** [comment]
This has since been approved.
