### ISSUE TITLE
Redundancy in SP800-56C algs + some spec confusion

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1085]
Hello,

The SP800-56Cr1 algs all seem to have "kdfType" as a field within their "kdfParameter" and "kdfConfiguration" arrays. This seems to be redundant as it doesn't seem that this value is subject to change within a single vector set which defines the alg being used itself.

In addition, there seems to be redundancy in the "kdfConfiguration" aspect of test groups - if this info is to be assciated with test cases, is there a need for this data to be included with both the test cases and the test groups? (hmacAlg, fixedInfoMattern, encoding).

These questions mostly come from a place of trying to understand if theres maybe edge case scenarios our software should be equipped for where these values can differ - it is also difficult to make assumptions as to which data to use if there are conflicting data between test groups/test cases, etc.

Finally, a small opinion, it might be nice if the "kdfConfiguration" object appeared before the test case array in JSON test groups. This makes it easier (in my opinion) to find all of the info associated with a test group in one place before digging into the test cases.

Thanks,
Andrew

**Comment by Kritner** [comment]
There is currently no differences between the group level configuration and the test case level parameter for many properties, the inclusion of both was just an oversight.

I'll look into changing the location of the kdfConfiguration object within the layout of the json as well as removing the redundant properties from kdfParameter for the next release.

This *could* potentially be a breaking change if an implementation was pulling kdf configuration/parameter information from the test case rather than the group (even though they're equivalent for things like `l`).

**Comment by abkarcher** [comment]
Thank you for the clarifications!

**Comment by livebe01** [comment]
I believe at least some of these issues have been addressed, e.g., encoding, pattern, and hmacAlg
