### ISSUE TITLE
KAS ECC Ar3 Full MQV "Specified argument was out of the range of valid values." after addition of KMAC in KC list

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP#1090]
Hi,

We are getting:
```[{"acvVersion":"1.0"},{"error":"Specified argument was out of the range of valid values. (Parameter \u0027capacity\u0027)"}]```
After adding:
```
"KMAC-256": {
                  "macLen": 512,
                  "keyLen": 256
                },
```
and
```
"KMAC-128": {
                  "macLen": 256,
                  "keyLen": 128
                },
```
to the capabilities request.

I could not find "capacity" in the spec.

I have attached the request and responses.

[Archive.zip](https://github.com/usnistgov/ACVP/files/5670448/Archive.zip)

Please let me know if you need any more information.

MW

**Comment by Kritner** [comment]
I'll take a look at this shortly, I have a pretty good idea of where the
issue is. I put some additional guards into our kmac implementation because
of a way a Kas kdf was invoking it incorrectly, apparently that same
incorrect behavior existed for key confirmation as well. I'll put a
correction in and update when the issue is resolved.

Thanks!

**Comment by Kritner** [comment]
Looks like my suspicion was correct.  The fix put in (and subsequent guards without our KMAC implementation) from https://github.com/usnistgov/ACVP-Server/issues/43 caused this response from the server.  Rather than create incorrect values due to a bad KMAC construction it threw an exception - overall better behavior IMO.

Thanks for the issue report, I'll get a fix in.

**Comment by Kritner** [comment]
The change is on demo, I'll update again once on production.  I re-ran the generation request from the vector set in the original issue, and the files have been generated.

**Comment by Kritner** [comment]
This change is now on demo and production in release [v1.1.0.14 hotfix 2](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14-2)
