### ISSUE TITLE
Validation Results Request workflow 

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#117]
I am now implementing the Validation Results Request workflow on the server side and I have an issue.

The response is indicated as including the tests results. I won't be able to do that for every vector set disposition value. I can always provide a disposition value for the overall vector set but I won't be able to provide any test specific results until all of the tests have run and the vector set is either in failed or passed state.

Will this be an issue? If not, we will need to document this behavior/option on the part of the server.

**Comment by hbooth** [comment]
Related to the Vector Set Request workflow, how long do we keep the results around?

**Comment by atvassilev** [comment]
@hbooth  I think this behavior is ok since eventually the detailed error status will be provided. So we can document in the spec that the client will receive the initial disposition value for the vector sets but will get the details all results have been processed by the server and final disposition of that set is determined. 

To your second question, I think we have talked about keeping data for 5 business days with the possibility to extend the time lease with a submission of results, good or bad. It would be good to get some feedback on this from the industry. I also think that we should reserve the right to tweak this depending on the capacity and load of the server.

**Comment by hbooth** [comment]
@atvassilev certainly this is all true for the vector sets, but we hadn't really discussed the validation results in any detail, and there isn't any guidance in the spec. i know we will need to expire them at some point it just isn't clear to me from reading the spec:
a) how the server should communicate when they will expire a priori
b) how the server should communicate the results have expired since the current expired meaning is in reference to the vector sets

I feel we will need some additional detail in the spec to cover all of the edge cases and am trying to log these issues to remind us/me to fix it when time allows

**Comment by atvassilev** [comment]
@hbooth and I discussed this issue yesterday and here is my recollection. Please correct me if some of the information is wrong.

1. Need to introduce a test session in the protocol that may span several vector sets. The session should have own status, similar to vector set - see below.

2. Vector sets have expiry property and it should govern the validity of test results for that vector set. If a validation request comes in with errors, the validity time interval on the vector set will be bumped by some amount, say 5 more business days, to allow debugging on the client side. This means that the validity of the test results implicitly gets extended. If the validation request comes and succeeds w/o errors, the server files a certificate and closes this vector set w/o bumping the expiry up. 

3. If a validation request comes to the server for a vector set that has expired, the server should return an error and report status expired. 

4. Managing the status for the test session is more complicated because the contained vector sets may have (slightly) different expiry dates. The server produces them in some order and sets the expiry property for each as it is created. Naturally, this takes time and any subsequent vector set may have a later expiry date. We need to decide i) does the session also have expiry and if so how to define it? One simple idea may be to set it to the longest expiry date for all included vector sets; ii) how to report the status of a session for which some of the vector sets have been validated OK, others have expired before successful validation.

**Comment by atvassilev** [comment]
now that we have introduced JWT with corresponding expiration policies, is this there anything more to do here?

**Comment by hbooth** [comment]
yes, the JWT only provides (a renewable) authorization to the test session it does not provide an explicit expiration of the test session instance in the database nor server management policies. I think this issue will hopefully be addressed by some of the future work in 0.5.

**Comment by atvassilev** [comment]
OK, at least we are partially there since we now have a test session established.

**Comment by Kritner** [comment]
Resolved from #392 as per PR message
