### ISSUE TITLE
SP 800-56C OneStep KDF Question - multiple AuxFunctions with varying inputs and outputs

### ISSUE THREAD

**Issue by mtdownz** [usnistgov/ACVP#1172]
**Protocol Section**
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-kdf-onestep.html#name-fixedinfopatternconstructio

**Protocol Question**
1. For 800-56C One Step KDF implementation that supports a domain of values for the "auxFunctions" field e.g. HMAC-SHA-256, HMAC-SHA-512, etc. How should a request be sent when the fixedinfopattern construction only allows for a single value for 'l' ( length of the derived keying material in bits) given the output of each auxFunction will result in differing lengths?
2. Similarly, for the set of domain values for 'z' that require a min/max and increment value, how can the output of EC be handled for all curve types e.g. 224, 233, 256, 283, 384, 409, 521? These are the z values for most approved EC curves which don't conform to a set increment?

Should the above implementation be handled as separate requests (e.g. limiting the z values and/or auxFunction to just one value at a time) into the same registration?

Thanks!

**Comment by Kritner** [comment]
> For 800-56C One Step KDF implementation that supports a domain of values for the "auxFunctions" field e.g. HMAC-SHA-256, HMAC-SHA-512, etc. How should a request be sent when the fixedinfopattern construction only allows for a single value for 'l' ( length of the derived keying material in bits) given the output of each auxFunction will result in differing lengths?

The intention for `l` was to match the largest `l` value that the IUT can produce, under the assumption that the IUT's implementation of the KDF can "inner loop" until the desired length of keying material has been produced.  Since this KDF testing is supposed to be suitable for any number of KAS SSC domain parameters, my impression was the `l` value wouldn't need to support anything more than a scalar; though in hindsight with hardware/software specific optimizations that may not be the case.

You *can* register multiple occurrences of the same algorithm, but if your implementation can support the full algorithm implementation (the inner loops) then there's no real reason for that.

> Similarly, for the set of domain values for 'z' that require a min/max and increment value, how can the output of EC be handled for all curve types e.g. 224, 233, 256, 283, 384, 409, 521? These are the z values for most approved EC curves which don't conform to a set increment?

Again here the idea is that the KDF can be used generically with any number of domain parameters and kas schemes, the safe prime groups, ec curves, and IFC modulo will all generate shared secrets (`z`) at a length >2x the security strength of the domain parameters chosen, so having a math domain of `z` that fully covers the range of domain parameters for *all* security strengths could for example cover that KDF validation against (potentially) all kas domain parameters - depending on other things such as the KDF aux algorithms being used (SHA512 as an example would be fully covering, where SHA224 wouldn't).
