### ISSUE TITLE
Unable to submit results when vector set has been archived

### ISSUE THREAD

**Issue by dmomy** [usnistgov/ACVP#1176]
I have sessions that have expired  which I have issued a get to update the expiration date on the session.  When trying to submit responses for the vector set I get the following error 
     "Validation error(s) on JSON payload.",
      "Unable to submit results when vector set has been archived"
 The sessions in question are:
167700,   167702 167705 167711 169192 167715  167731  167694 177253 177254  167718 167720 167725  167723 167728 177255 177256  169056

**Comment by shaneshaffer** [comment]
Test Sessions 177253-177256 are irrelevant, as they are only about a week old.
All the other test sessions were created in March, and you didn't touch any of them until yesterday, when you touched 167700. They all expired 30 days after the day they were last touched, which was the day they were created for most, and a few days later for the others.
Expired test sessions cannot be resurrected by attempting to touch them. You can extend the expiration date prior to expiration, but not after (due to a minor oversight that will be corrected it may look like you've extended the expiration date, but you haven't - once it has expired, it is gone forever).
