### ISSUE TITLE
Key wrap test of direction and cipher combinations

### ISSUE THREAD

**Issue by swkeypair** [usnistgov/ACVP#1179]
[SP 800-38F defines KW-AE as "encrypt" using the forward cipher](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-38F.pdf#page=22), and defines unwrapping KW-AD as "decrypt" using the inverse cipher.  However, in ATF request vectors seemingly inappropriate combinations of "direction" and "kwCipher" are tested:

> "testType": "AFT",
> "direction": "encrypt",
> "kwCipher": "inverse",

Is this the correct interpretation of the standard?

For example, why is the encrypt operation to be tested using the inverse cipher when it is not defined as such in KW-AE?

**Comment by Kritner** [comment]
From https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-38F.pdf#page=16

![image](https://user-images.githubusercontent.com/8814983/119363431-cc542d00-bc7b-11eb-8b75-79fa3e0fd15c.png)

The underlying cipher of the key wrapping algorithm can be "cipher" or "inverse", then there is the `W` (wrap / auth encrypt) and  `W1` (unwrap / auth decrypt).

This gives several "combinations" of parameters that go into what the IUT performs as it relates to the test group / test case

| Operation | Cipher | underlying AES operation |
| --- | --- | --- |
| Wrap (direction encrypt) | Cipher | aes encrypt |
| Wrap (direction encrypt) | Inverse | aes decrypt |
| Unwrap (direction decrypt) | Cipher | aes decrypt |
| Unwrap (direction decrypt) | Cipher | aes encrypt |

![image](https://user-images.githubusercontent.com/8814983/119365706-35d53b00-bc7e-11eb-99bd-73e629899daa.png)

In the above `CIPH_k` can be either "cipher" (encrypt) or "inverse" (decrypt). 

Hopefully that makes sense... basically you can "Wrap" a key using a aes decrypt as the cipher (this would be the "inverse" cipher invoke), then the "Unwrap" would utilize the opposite of that - encrypt.  Vice versa also works using the encrypt operations as the "wrapping" cipher, and decrypt operation as the "unwrapping"; I called it out in the opposite direction first, because it seems less intuitive to utilize the algorithm in this operating mode (IMO).

**Comment by swkeypair** [comment]
OK - please confirm or correct:
For an implementation that supports key wrap (using the AES encrypt primitive) and unwrap (using the AES decrypt primitive), then the corresponding registration parameters (independent of other selections) would be:
"algorithm": "ACVP-AES-KW", "revision": "1.0",
            "direction": ["encrypt", "decrypt"],
            "kwCipher": ["cipher"],
...

Thank you

**Comment by Kritner** [comment]
that's correct

**Comment by swkeypair** [comment]
OK thank you.
IMHO, this could be made clearer in the ACVP specification and perhaps avoid some confusion.
Then again, maybe it is just me.

OK to close - thank you for your help.

**Comment by Kritner** [comment]
Thanks @dmchodnicki, closing as per #1223
