### ISSUE TITLE
question about range of DataUnitSeqNumber range in AES-XTS when tweakmode is "number"

### ISSUE THREAD

**Issue by rnunez83** [usnistgov/ACVP#1217]
[1] https://github.com/usnistgov/ACVP/blob/master/src/symmetric/sections/05-capabilities.adoc

[2] https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/aes/XTSVS.pdf

**Protocol Question**
In section 6.2 of the AES-XTS Validation System specification document[2] used for testing using the legacy CAVS tool, it stated that the "DataUnitSeqNumber is a base-10 number ranging between 0 and 255." 

In the capabilities section of the ACVT standard [1] there is no indication of the range that is used by the ACVP server when specifying "tweakMode" method as "number". What I would like to know is whether the parameters for testing AES-XTS using ACVTS remain within a range will be between 0-255?

**Comment by Kritner** [comment]
Yes the range continues to be 0-255, feel free to update the specification to note that.

**Comment by rnunez83** [comment]
thanks for the confirmation.

**Comment by swkeypair** [comment]
Digging into this to support a vendor trying to make the XTS testing work in a SATA compliant hardware device, we noted a few things that may help clarify this test under certain circumstances. After working through this, I searched this repository for an issue related to XTS and _tweakMode_ or _tweakValue_ and found this issue, and would like to suggest an edit to the description of _tweakMode_ in Table 3 of the ACVP specification of XTS.

SP 800-38E points to IEEE 1619-2007 (which requires purchase). The 1619 document is a bit vague about _tweakValue_ and as well alludes to the use of a sequence number. In some circumstances (apparently related to data unit size) the sequence number is used in direct replacement of _tweakValue_. Note for example the set of vectors in the Appendix under the heading "applied for a data unit of 512 bytes".

The XTSVS.pdf document fills in a missing piece of the solution, describing the _Data Unit Sequence Number_ (DUNS) option. As an aside, it is hard to pinpoint the origin of DUNS as a term, but conceptually it appears to be like a Logical Block Address (LBA). From an algorithm validation system perspective, IEEE-1619 / SP 800-38E appear to be met as long as the _tweakValue_ / _sequenceNumber_ is unique per block.

As @rnunez83 noted in creating this issue, the ACVP specifications are not clear about the range limitation when used as _sequenceNumber_. A suggested edit to [Table 3](https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#table-3) (Section 7.3) for _tweakMode_ Description:
> Determines the JSON value name, format and range of the AES-XTS tweak value input. Hex corresponds to the use of the JSON object _tweakValue_ presented as a 16-byte literal hex string. Number corresponds to the use of _sequenceNumber_ presented as  an integer number with a value in the range 0-255. For additional background, see [XTSVS.pdf](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/aes/XTSVS.pdf#page=7) Section 6.2.

Perhaps it would be better to import aspects of the XTSVS.pdf into the ACVP specification page rather than cite it, given that it is obsoleted by the ACVP specifications. In a number of places, ACVP specifications are missing the kind of information that was available in the older validation systems documents, such as how the test worked and not just the JSON formatting specification.

**Comment by livebe01** [comment]
Hi @swkeypair. Appreciate you providing this feedback. Sure we can update the spec to clarify the items you mention. When it comes to the new specs vs the old CAVS documentation, I see what you mean. I think part of the reasoning why we didn't lay out the explicit details of how we form the test cases based on the provided registrations is that the ACVTS testing is more involved/complex than the CAVS testing and it would be too involved to document that. Also, part of the intention w/ the ACVP algorithm specs is that anyone could use them to create a testing system. So, however a person/organization chooses to implement the testing for a spec is up to them. They weren't created to solely document how NIST implements ACVTS. Although, I think NIST/CAVP is the only organization using/developing them at this time.

It's not a replacement for good documentation, but I did want to mention that we recently posted our code [here](https://github.com/usnistgov/ACVP-Server) if you're ever interested in seeing how we've implemented something in ACVTS. 

[This](https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files) part of the repository holds example test session files for each of the algorithms we support and is especially helpful.

**Comment by livebe01** [comment]
@swkeypair I just updated the symmetric spec to address the items you mentioned. I noticed that the entry for tweakMode in Table 12 was missing, so I added it. I also updated the tweakMode entry in Table 3 and the tweakValue and sequenceNumber entries in Table 17. Thanks for the feedback and help!

**Comment by swkeypair** [comment]
Great - the changes make it much clearer in my view. 
Thank you!
