### ISSUE TITLE
RSA decryption primitive testing: Test Enhancement

### ISSUE THREAD

**Issue by kaleb-himes** [usnistgov/ACVP#1219]
My organization has multiple module versions and many OEs' on [cert 3389](https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3389). We are adding more OEs' all the time. We run the RSA Decryption Primitive test 2-3 times a month. As of now, our implement for this test (given the hard count failure requirement) is to use the `totalFailingCases` count provided in the REQUEST file and track the number of failures our harness has gotten so far with a variable `numberOfFailures`. Our harness supports two scenarios:

Scenario 1) Once the `totalFailingCases == numberOfFailures`, any tests that fail after that, our harness will run the decrypt over and over and over .... and over and over until we get a successful decrypt. This is the most common case being executed by our test harness.

Scenario 2) If our harness reaches the end of the vector set and `totalFailingCases > numberOfFailures`, our harness will re-run the file again (up to X number of retries), I have our ceiling at 30 retries for the entire file but I've never needed more than 2 when re-running the entire file. This scenario is rare for our harness to execute and I have only seen it happen when processing DEMO vector sets, never on PRODUCTION vector sets.

It is not uncommon to encounter cipherTexts that take 250 (+/- 50) attempts before we get a successful decrypt once we have enough failures. However, I just ran into a vector set that has a cipherText that failed to decrypt after 500,000+ attempts (Scenario 1 above). I finally had to write our FIPS lab and tell them we got a bad set from the ACVP server and request that we receive a new PRODUCTION set. In the 50+ DEMO and PRODUCTION sets our harness has processed this year, the above has never happened before. This one case does seem to indicate that there needs to be an improvement to this test approach. Perhaps the ACVP server could at least confirm each cipherText can be decrypted before sending off the requests to be processed by the IUT?

**Comment by kaleb-himes** [comment]
On a side note, given that this is a moving target, would it make more sense to have a floor value instead of a hard-count?

IE instead of `totalFailingCases` have `minimumFailingCases`?

In the older CAVP tests we just had to get AT LEAST 10 failures, there was no hard requirement for EXACTLY 10 failures, why has this changed?

**Comment by celic** [comment]
As we went through these tests, we thought the RSADP tests would only be run a couple of times per year, as they are a requirement for the NPIVP process, beyond CMVP. It turns out there are _some_ applications of SP 800-56Br2 where these tests are necessary as well. 

I've never liked this testing strategy for this algorithm. It relies too much on the harness to perform a matching game than actually run the tests. We do try to help the user out in the test case generation though. The server will randomly select `totalFailingCases` test cases and force those ciphertexts to have two leading `1` bits. This should make it easier for the client to find a failing key. With this in mind, is it possible to rework the harness a bit to adjust? Though, to balance out, we do nothing on the other test cases. They _could_ potentially pull a value with many leading `1` bits and just be very difficult to find a key that can decrypt successfully. This is a shortcoming of the tests for sure where we require an exact number of failures. I would prefer to keep a specific number of failures (a range may be acceptable, but we need to see both successful decrypt and unsuccessful decrypts.) We could adjust by forcing the leading bits to be `0` in the "expected success" cases, so that finding a key that can decrypt is much easier (and always possible). 

Either way, we should describe this testing process a bit in the documentation so that harnesses are able to know when a failing decrypt is acceptable and when it should try another key.

**Comment by celic** [comment]
Also, either through here or separately could you please inform me what lab you are working with? Email is christopher.celi (at) nist.gov.

**Comment by kaleb-himes** [comment]
@celic, Gladly. Sent you a direct email with details of our FIPS lab.

I appreciate the feedback very much!

> The server will randomly select totalFailingCases test cases and force those ciphertexts to have two leading 1 bits. This should make it easier for the client to find a failing key. With this in mind, is it possible to rework the harness a bit to adjust?

Yes, I can see an adjustment to our harness to check (pseudo code):

```
if (result != ACVP_SUCCESS && the two leading bits are 1's) {
    re-run this cipherText 5-10 more times(); /* Play around with the 5-10 threshold, perhaps it can be reduced or needs increased, time will tell */
    if (still failing after that then treat as a legitimate failure);
}
```

Warm Regards,

KH
