### ISSUE TITLE
SHA LargeDataTest "Optional" Status

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#1251]
Hello,

The current status of large data testing on SHA is that it is an optional test. after reading through #1016 , it is still not entirely clear to me what that entails. Is it completely optional, or only optional in the sense that implementations not designed to process larger message sizes do not need to test it? Is it required for implementations that can support larger data sizes?

If it is not currently required for implementations that could support it, is there any intent to make it required in the future? How would one determine what large data test sizes to test if an implementation is not very choosy?

Thanks,
Andrew

**Comment by Kritner** [comment]
@celic perhaps you can elaborate - but the idea of the test came up as a means of giving additional assurances for hash functions that implement a `Hash(message)` interface, rather than (or likely in addition to) the `Init()`, `Update(...)`, `Final(...)` methods.

Right now, the LDT is not required as you indicated, I can't speak to if it will ever be required.  As far as which large data sizes to test against, like most capabilities registrations, your IUT should register with as many capabilities supported as possible, ideally.  Since this particular capability takes in an array of large sizes to test, you could conceivably register against all of them.

-----

> The current status of large data testing on SHA is that it is an optional test. after reading through #1016 , it is still not entirely clear to me what that entails

I'm not sure if this is asking about the specifics of the test itself from the ACVP perspective, or if it's more about the motivation of the test.  I'm going to assume it's the latter, since the former is detailed between #1016 and the linked https://eprint.iacr.org/2019/1421.pdf.

Given

```json
{
	"largeMsg": {
		"content": "28AE5105BDF225CD",
		"contentLength": 64,
		"fullLength": 34359738368,
		"expansionTechnique": "repeating"
	}
}
```

as the large message to use in an LDT test case, the IUT is expected to expand the given 64 bits (`contentLength`) of `28AE5105BDF225CD` (`content`) to a full message at a length of `34_359_738_368`  (`fullLength`) bits, repeating the content until the full bit length is reached.  At the point of having the fully expanded message, the IUT is to run the message in its entirety through ideally a `Hash(message)` function (rather than Init, Update, Final), in order to help assure problems like the one described in https://eprint.iacr.org/2019/1421.pdf are avoided.

**Comment by celic** [comment]
In terms of the CAVP, the test is fully optional. You may include it if you wish. For the CMVP, there are situations where a reviewer would need to see the test appear. We are working on identifying those situations at the moment. But ultimately the test will always be optional for the CAVP because we do not know enough about the module to determine if the testing is required. 

If you include the `"performLargeDataTest"` array in your registration then the tests will be included in the resulting JSON files.

**Comment by abkarcher** [comment]
Hello,

Thank you both very much for the details and insight! It is good to know this may come up in CMVP in the future. 

Closing-
Thanks,
Andrew
