### ISSUE TITLE
RSA KTS OAEP

### ISSUE THREAD

**Issue by seamusgr** [usnistgov/ACVP#1275]
**Protocol Section**
OAEP Basic no confirmation

**Protocol Question**
"scheme": "KTS-OAEP-basic",
            "kasRole": "initiator",
            "keyGenerationMethod": "rsakpg1-basic",
            "modulo": 2048,
            "fixedPubExp": "010001",
            "l": 256,
            "iutId": "7400",
            "serverId": "434156536964",
            "ktsConfiguration": {
                "hashAlg": "SHA2-256",
                "associatedDataPattern": "algorithmId||l||uPartyInfo||vPartyInfo",
                "encoding": "concatenation"
            },
            "keyConfirmationDirection": "",
            "keyConfirmationRole": "

In the response for the scheme above.  Is the dkm to be included in the  encrypted data or is it just the fixed data which needs to be encrypted.  If it is included is it simply appended or does it require a separator

**Comment by Kritner** [comment]
I'm not sure if I'm understanding what you're asking.

For KTS basic from the initiator perspective, the IUT is expected to return a C value and DKM. This information can also be retrieved through a `isSample` registration, and pulling from the "expected results" endpoint: `/acvp/v1/testSessions/{{testSession_Id}}/vectorSets/{{vs_id}}/expected`

It's been many months, but if I'm remembering correctly, for this test the IUT is given the public key of the Server, then IUT is expected to come up with a `DKM`, which is constructed through the OAEP process and results in a `C` value.  For the acvp server to be able to verify an appropriate `C` value was reached, it needs both the `C` and `DKM` in the response file.  The candidate `dkm` is recovered from `C`, then compared to `DKM` to verify.

**Comment by smuellerDD** [comment]
Am Mittwoch, 10. November 2021, 17:22:52 CET schrieb Russ Hammett:

Hi Russ,

> I'm not sure if I'm understanding what you're asking.
> 
> For KTS basic from the initiator perspective, the IUT is expected to return
> a C value and DKM. This information can also be retrieved through a
> `isSample` registration, and pulling from the "expected results" endpoint:
> `/acvp/v1/testSessions/{{testSession_Id}}/vectorSets/{{vs_id}}/expected`

The initiator works - it is encryption.

The issue is the responder which has to perform the decryption. The ciphertext 
that is provided cannot be decrypted by two independent implementations due to 
OAEP padding errors.

> 
> It's been many months, but if I'm remembering correctly, for this test the
> IUT is given the public key of the Server, then IUT is expected to come up
> with a `DKM`, which is constructed through the OAEP process and results in
> a `C` value.  For the acvp server to be able to verify an appropriate `C`
> value was reached, it needs both the `C` and `DKM` in the response file. 
> The candidate `dkm` is recovered from `C`, then compared to `DKM` to
> verify.

This is not the issue.

The issue is where the server provides C. My IUTs cannot recover DKM from C 
due to OAEP padding issues.


Ciao
Stephan

**Comment by Kritner** [comment]
@smuellerDD are you working with @seamusgr on this issue separately?  The original post specifically called out from an IUT initiator perspective, where it sounds like you're describing something more like your issue opened https://github.com/usnistgov/ACVP-Server/issues/156 which would be from a responder perspective, no?

**Comment by smuellerDD** [comment]
I apologize - I just saw OAEP without checking the issue number. This is not my thread. Please excuse my noise.

Ciao
Stephan

—
Cui bono?

**Comment by seamusgr** [comment]
@Kritner correct.  When there is no fixed input parameter the test passes.  It is when the fixed input string is part of the test as indicated above it fails.  So I believe my formatting is incorrect. Do you know if the dkm should follow the fixed input or should even be included at all
thanks

**Comment by Kritner** [comment]
I still don't understand what you mean by:

> Do you know if the dkm should follow the fixed input or should even be included at all

Where are you talking about? In the response files? In the crypto itself?  I just need more context and specificity as to what it is that's being asked about.

If you're talking about the crypto portion, the "fixed input" I'm assuming you're referring to the associated data, and that data is constructed based on the pattern provided.  In your case the pattern `algorithmId||l||uPartyInfo||vPartyInfo` would mean the concatenation of the `algorithmId`, 32 bit `l` value, `uPartyId`, `uPartyEphemeralData`, `vPartyId`, and `vPartyEphemeralData`.  There are numerous closed issues between this repo and https://github.com/usnistgov/ACVP-Server/ that go into further detail the specifics of that construction.  

From the crypto perspective, this is how the associated data "fits into" the algorithm:

```cs
// 3. OAEP encoding:
// a. Apply the selected hash function to compute: HA = H(A).
var HA = _sha.HashMessage(additionalInput).Digest;

// b. Construct a byte string PS consisting of nLen – KLen – 2HLen – 2 zero bytes. The
// length of PS may be zero.
var PS = new BitString(new byte[nLen - KLen - 2 * HLen - 2]);
	
// c. Concatenate HA, PS, a single byte with a hexadecimal value of 01, and the keying
// material K to form data DB of nLen – HLen – 1 bytes as follows:
// DB = HA || PS || 00000001 || K
var DB = HA
  .ConcatenateBits(PS)
  .ConcatenateBits(BitString.To8BitString(0x01))
  .ConcatenateBits(keyingMaterial);
```

Where `additionalInput` is the concatenation mentioned previously.  In a "no additional input" scenario, this `additionalInput` is just an empty bitstring that is then hashed to make up `HA`.

-----

If you're asking about something in the expected response, the constructed associated data is never transmit or expected to be transmit in the prompt or response files.  *Pieces* of data that *make up* the associated data is a part of the prompt file (like the `algorithmId`, `l`, and `party` information, but the construction of the concatenation is up to both parties to do in a consistent manner in order to ensure that part of the crypto routine is implemented correctly.

**Comment by seamusgr** [comment]
@Kritner   this is helpful
(1) I missed the 32bit size of the '1' divider for the fixed string.  i will fix this.  
(2) Also I missed the 32bit divider between the fixed string and the Keying material. This was the source of my original question

I appreciate your attention. I will ping back on whether this works

**Comment by seamusgr** [comment]
@Kritner  thank you for your help. I had completely misread the semantics of the test and believe now have located my problem. I was considering the fixed input as part of the string to be encrypted rather than playing a role in the encryption algorithm.

**Comment by Kritner** [comment]
No problem!  I wasn't sure on if you had all the information you needed to close out the issue, but if I don't hear back in the next few days I may close it out.

**Comment by seamusgr** [comment]
Thanks again for your help.  I will close out this issue
