### ISSUE TITLE
RSA keyGen &  KeyinfoGeneratedByServer

### ISSUE THREAD

**Issue by davyrouillard** [usnistgov/ACVP#1276]
Hello,

**Protocol Section**
https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#name-rsa-algorithm-registration-

**Protocol Question**
I have generated tests on the demo server for RSA keyGen, setting infoGeneratedByServer to false and true. (see attached files [keyGen_files.zip](https://github.com/usnistgov/ACVP/files/7693619/keyGen_files.zip))
In both cases, I obtain key values from the server when I expect that the server will send empty test cases.
Could you please help me to understand this behaviour?
Thanks you,
Davy

**Comment by livebe01** [comment]
Hi @davyrouillard, I just took a look at the capabilities file you provided and noticed that the value for isSample is true. In the case of RSA keyGen, the use of `"isSample": true` trumps the value you're providing for infoGeneratedByServer. Ordinarily, setting infoGeneratedByServer to false would result in your receiving mostly empty test cases. However, because isSample is set to true, ACVTS must generate (and provide) these values in order to calculate the expected results (see [here](https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#section-12.16-3.1.1) and [here](https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#name-retrieve-expected-results)). If setting isSample to false does not solve your issue, please let me know.

**Comment by davyrouillard** [comment]
Hi @livebe01,
Oh yes, this makes perfect sense and I am sorry I was not able to solve it alone.
Once "isSample" set to False, that's working as expected.
Thanks you very much for the answer.
