### ISSUE TITLE
Unable to download test session after successful login and capabilities registration

### ISSUE THREAD

**Issue by markSimonton** [usnistgov/ACVP#1279]
this is more of a help request than a bug report.  I am attempting to update our  ACVP vector request/submission tool;  an older version of the tool is working, but limping along as occasionally it will fail to download vectors.  My current version can:
* login
* register a set of Capabilities 
* create a test session directory structure on the client
* FAIL to download a set of test vectors for the test session

I don't yet have full visibility to the outgoing and incoming messages, I am still learning QT, but here is an edited version of the debug output that I am seeing:

shared secret size 48
offset 3
"POST"  path /acvp/v1/login
onLoginReply

===========================
TestSessionAcvpRestClient::registerCapabilities
============================
registering capabilities
 "[{\"acvVersion\":\"1.0\"},{\"algorithms\":[{\"algorithm\":\"DSA\",\"capabilities\":[{\"gGen\":[\"unverifiable\"],\"hashAlg\":[\"SHA2-256\"],\"l\":2048,\"n\":256,\"pqGen\":[\"probable\"]},{\"gGen\":[\"unverifiable\"],\"hashAlg\":[\"SHA2-256\"],\"l\":3072,\"n\":256,\"pqGen\":[\"probable\"]}],\"mode\":\"pqgVer\",\"prereqVals\":[{\"algorithm\":\"SHA\",\"valValue\":\"same\"},{\"algorithm\":\"DRBG\",\"valValue\":\"same\"}],\"revision\":\"1.0\"}],\"isSample\":false}]"
"POST"  path /acvp/v1/testsessions
"headers\nHTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\nContent-Type: application/json; charset=utf-8\r\nServer: Microsoft-IIS/10.0\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload\r\nDate: Tue, 28 Dec 2021 17:57:02 GMT\r\n\r\n"

"downloading /acvp/v1/testSessions/222183/vectorSets/832440"
"GET"  path /acvp/v1/testSessions/222183/vectorSets/832440
"headers\nHTTP/1.1 403 Forbidden\r\nTransfer-Encoding: chunked\r\nServer: Microsoft-IIS/10.0\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload\r\nDate: Tue, 28 Dec 2021 17:57:27 GMT\r\n\r\n"

any help about how to interpret the messages I am seeing would be helpful

**Comment by Kritner** [comment]
Hey @markSimonton are your get requests against `/acvp/v1/testSessions/222183/vectorSets/832440` using the JWT returned at login, or the one at registration?  I would *guess* that your tool isn't assigning the JWT properly for those requests.

The login JWT has no claim to test sessions, the JWT that is in the response against the POST `/testSessions` endpoint will have a claim in it that grants access to that specific test session.  Separately, if your tool happens to register multiple test sessions, you'll need to internally track which JWT belongs to which test session, as a JWT for test session 222183 will not work for test session 22184, even if both test sessions were created by you.

**Comment by markSimonton** [comment]
please forgive my ignorance.  What is JWT?  As for mixing the test session request, from my point of view, I am still in the same login session, I request a new test session and immediately request the download of vector file.  for the session above I used an edited capabilities file with only 1 test type "symcrypt"
				"algorithm": "DSA",
				"mode": "pqgVer",
				"revision": "1.0",

this capabilities request worked last month, but is not working for my modified version of our software;  also note my predecessor added code in an attempt to automate the request for vector files, then removed some of the code and then moved to a different project.
the test session file looks like this (edited TOTP)
[{"acvVersion":"1.0"},{"accessToken":"eyJh...TxqQ","capabilitiesFile":"C:/Users/v-masimonton/xfer/Vectors/acvp/v1/testSessions/222183/SymCryptDSA.json","createdOn":"2021-12-28T12:57:02.2114648-05:00","expiresOn":"2022-01-27T12:57:02.211466-05:00","isSample":false,"passed":false,"publishable":true,"retry":null,"testSessionFile":"C:/Users/v-masimonton/xfer/Vectors/acvp/v1/testSessions/222183/tsSymCryptDSA.json","url":"/acvp/v1/testSessions/222183","vectorSetUrls":["/acvp/v1/testSessions/222183/vectorSets/832440"]}]

**Comment by Kritner** [comment]
The `accessToken` is the JWT in the response from both the `/login` and `/testSession` post endpoints.  JWT are basically encoded and signed pieces of data that state claims/authorization to specific resources.  Just for clarities sake, the TOTP is a time based one time password tied to your client certificate required to successfully authenticate on the `/login` endpoint; as opposed to the access token(s) which are JWT and provide authorization to resources.

You can paste your JWT into a website such as https://jwt.io/ to look at the claims (key/value pairs) contained within the JWT - though keep in mind that JWT, much like your client certificate and TOTP seed should be kept secret.  A JWT that has no `tcId` or `vsIds` claims means it's a login JWT, rather than a test session JWT.

Test sessions can only be accessed by JWT that have claims into that specific test session.  Just as an example for your test session 222183, with (at a minimum) vector set 832440, you should have the following claims in your unencoded JWT:

```
{
  "tcId": 222183,
  "vsIds": [832440]  
}
```

I may have gotten the data type incorrect on the above claims, I don't have a JWT handy to reference... but either way that JWT would have to be passed in the header of requests against that test session and vector set.

**Comment by markSimonton** [comment]
I used the web page you mention, and this is the information 
```
# decoded JWT
header
{
  "alg": "HS256",
  "typ": "JWT"
}
Payload: data
{
  "tsId": "222183",
  "vsId": "[832440]",
  "sub": "E=v-masimonton@microsoft.com, CN=Mark_Simonton, OU=Developer, O=Microsoft Corporation, L=REDMOND, S=WA, C=US",
  "nbf": 1640714222,
  "exp": 1640716022,
  "iat": 1640714222,
  "iss": "NIST ACVP DEMO"
}

```
so the JWT seems to present the proper information.

**Comment by Kritner** [comment]
That particular JWT expired on December 28th, so it's possible that it has been expired since your initial 403 when opening the issue.  You can use the `/login` endpoint and your expired JWT to have a new one issued: https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#name-login

I don't know if that was actually the problem here or not, but I would try to refresh your token and query `/acvp/v1/testSessions/222183/vectorSets/832440` again.

**Comment by Kritner** [comment]
This issue seems pretty stale, so I'm closing but feel free to bump/reopen if there's something outstanding.
