### ISSUE TITLE
RSA sigVer primitive cannot be ACVP tested?

### ISSUE THREAD

**Issue by hbarton-atsec** [usnistgov/ACVP#1347]
How come the RSA sigVer primitive doesn't have an ACVP test? Right now we have this below:

- RSA encryption w/ public key (aka RSA key encapsulation encryption) - KTS-
IFC-SSC

- RSA decryption w/ private key (aka RSA key encapsulation decryption) - KTS-
IFC-SSC

- RSA encryption w/ private key (aka RSA signature generation primitive / RFC 
3447 RSASP1) - RSA sigprim/decprim

- RSA decryption w/ public key (aka RSA signature verification primitive / RFC 
3447 RSAVP1) - NOT TESTABLE

**Comment by livebe01** [comment]
I pinged Chris, but I suspect that CAVP FAQ GEN.2 is your answer (pasted below).

GEN.2 Is it acceptable if an implementation of an algorithm is presented in such a manner that the end user using the implementation must make calls to several functions in order to perform a major function of the algorithm (for example, Signature Generation)?

Generally, no. NIST expects that all the parts of an implementation of an algorithm will be contained within one executable (or its equivalent in firmware or hardware) and that one call to the algorithm implementation will determine which of the underlying functions are executed, how these underlying functions are executed, and in what order these functions are executed. For example, in a PKCS1.5 implementation, as the PKCS#1 v2.1 document states, we would expect that a call to RSASSA-PKCS1-V1_5_SIGN would call EMSA_PKCS1_V1_5_ENCODE and RSASP1. The ACVTS testing has been designed to assure that the functionality of the underlying functions within an algorithm implementation is operating correctly. If all the parts are supplied to an end user with the ability to put them together any way possible, there is no guarantee that they will be called in the order specified by the standard for that algorithm. Therefore, we cannot validate this implementation as a completed implementation. Providing instructions in the Security Policy as to the fixed order of operations of component functions is also not acceptable.

However, there are cases where two or more distinct entities in a system cooperate to execute an algorithm, such as the case of a smart card and a smart card reader. In this case the functions that comprise the digital signature algorithm are divided between the two parts of the system, card and reader, and the order of operations is fixed so that there is no way for the component functions of the algorithm to be called out of order.

The testing of individual algorithm components was introduced in 2011. Several situations have led to this new type of testing. For example, PIV cards have limited processing space and therefore some parts of the algorithm are performed off card.

In the case of FIPS 180 and FIPS 202 that define the SHA family of hash functions, a common implementation interface uses Init, (at least one) Update, and Final as three successive calls. This is an allowed exception to this rule. The same exception applies to FIPS 198 that defines HMAC, and SP 800-185 that defines eXtensible Output Functions (XOFs).

Where the standard identifies individual operations that comprise the cryptographic operation, such as SP 800-90A for DRBG, follow the requirements of the standard.

**Comment by hbarton-atsec** [comment]
Hi Chris,

I'm bringing this thread back up as I have a similar question related to your last comment. SP 800-56B Rev. 2 mentions RSAEP in section 7.1.1 so why is there no specific testing available for it?

**Comment by celic** [comment]
It's in progress.

**Comment by celic** [comment]
Oh sorry, specific RSADP testing for 56B will be available soon. We did not
discuss RSAEP, but could easily introduce it shortly after.

**Comment by smuellerDD** [comment]
Am Donnerstag, 9. Juni 2022, 16:58:16 CEST schrieb Chris Celi:

Hi Chris,

> RSA SigPrim and DecPrim are both mentioned by name in the SP 800-56 series.
> Others, while defined by RFCs, I do not believe are mentioned in NIST
> standards as prerequisites for other algorithm tests. Implementing them may
> be useful for debugging some implementations, but we have not seen a ton of
> value from the existing primitive tests, and have not looked towards
> extending them to other primitives.

Thank you for the clarification.

Ciao
Stephan
