### ISSUE TITLE
HMAC: "Domain" data type definition inconsistent

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#223]
The HMAC specification defines in section 2.2 the data type "Domain". The example for keyLen indicates a range, but the example for macLen indicates an array.

Which is it?

**Comment by Kritner** [comment]
`keyLen` data type differs between CMAC-AES and HMAC.  For CMAC-AES, since there are only 3 valid `keyLens`, a `int[]` was used.  With HMAC, since a large number of `keyLens` are available, a `Domain` is in use.  #222 goes into some of this information in more detail.  Let me know if you need anything else with this issue.  Thanks!
