### ISSUE TITLE
CMAC definition: keysize of TDES

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#224]
In the symmetric cipher definition, TDES is defined to have 168 bit keys. In the CMAC definition, the keysize seemingly is 192 bits. Please use consistent key sizes.

The CMAC-TDES example in appendix A does not contain a keyLen definition and thus would not be consistent with the spec.

**Comment by Kritner** [comment]
@smuellerDD this appears to be a miss in the spec, TDES does not actually specify a `keyLen` in the registration, as there is only one valid `keyLen` for TDES.  192 bits is the expected `keyLen` (though the keys are split into 8 byte chunks) for TDES, however only 168 of those bits are the "actual key" since there is a parity bit per byte.

I'll issue a PR cleaning up some of the ambiguity in the specification.

**Comment by Kritner** [comment]
I believe this spec discprepancy has been addressed in #225.  If not, feel free to update.
