### ISSUE TITLE
Update `failureTest`/`decryptFail` to be "in the positive"

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#244]
I'm not sure of the correct way to phrase this, but it's likely to be less confusing to change instances such as:

```
"decryptFail" : true // test is a failure
"decryptFail" : false // test is a pass
"failureTest" : true // test is a failure
"failureTest" : false // test is a pass
"result" : "pass"
"result" : "passed"
"result" : "fail"
"result" : "failed"
```

to

```
"testPassed" : true // test is a pass
"testPassed" : false // test is a failure
```

The `isSuccessFulTest` negates potential double negatives, as well as changes the language to be more general, not specific to "decrypt/encrypt".

Thoughts?  I'm not super set on `isSuccessfulTest`, but I feel like the current should be updated.

**Comment by atvassilev** [comment]
I agree the original definitions are very confusing/awkward. I am a bit hesitant about the choice of words for the new definition because SuccessFulTest may also be interpreted ambiguously. For example, it may mean what you imply but it also may mean that I was successful testing something, regardless of the outcome of the test. For example, I succeeded testing my AES implementation meaning I was able to connect to the server, register, get test data, run through the algorithm, submit the results and get a verdict. This is a successful test. Now, the verdict may a pass or fail. 

I hope I am not over-engineering this. How about testPassed?

**Comment by Kritner** [comment]
fine by me, is this something we could get penciled in for .5?

**Comment by atvassilev** [comment]
I am in favor. Let's see if somebody else chimes in before committing to v0.5.

**Comment by Kritner** [comment]
This is not necessarily a comprehensive list (i can edit it, or other can) but the algos that have instances related to this issue are:

AES-GCM
AES-XPN
AES-CCM
CMAC
DSA-PQGVer
DSA-SigVer
ECDSA-KeyVer
ECDSA-SigVer
KAS-ECC
KAS-FFC
AES-KW
AES-KWP
TDES-KW
RSA-DPComponent
RSA-KeyGen
RSA-LegacySigVer
RSA-SigVer
RSA-SPComponent

**Comment by bfussell** [comment]
These all vary greatly wrt what they are testing, so I assume we want something as generic as possible that represents all of them. Why not something simple like you suggested above ?

"result" : "pass"  or "success"
"result" : "fail"

The test result represents decrypt operations for the symmetric algorithms or keywrap and it seems clear to me for verify operations as well.  Are there any that don't fall into the category of "the test result is a failure"  or "this test result is a success or passed" ?  If not, then this should suffice.

**Comment by Kritner** [comment]
Yeah the symmetric ciphers are what I have most of my experience with from the gen/val end, but I was thinking things like `SigVer` would work pretty well with the `bool` "testPassed" over the `string` "result".

@bfussell can you think of any specific situations where something like `"testPassed" : false` wouldn't work out well from an IUT perspective?

**Comment by bfussell** [comment]
Not completely intuitive to me, but I'll follow the majority here.  The way I look at it a successful test sometimes means a failed decrypt or a failed verify.  The result is a failure not the test, the test successfully ran as expected. testPassed : false just sounds like the test wasn't successful  - to me :)

**Comment by Kritner** [comment]
ah I understand what you mean.  My biggest thing was like you pointed out, getting something that worked in all cases where something "failed to happen", while being a `bool` as to just avoid one more magic string.

**Comment by atvassilev** [comment]
@bfussell I see things differently. Each test has an intended outcome and passing or failing means reaching this outcome or not. I think testPassed captures this well and is boolean to simplify handling on the server.

**Comment by bfussell** [comment]
@atvassilev I'm fine with a true/false boolean,  just having a hard time with the fact that  "testPassed" : true does not mean that the test passed and "testPassed" : false does not mean that the test failed. Test pass/fail disposition is determined by the server not the client. It's more of an operationSuccess status rather than test, but I'm not really sure that's much better.

**Comment by atvassilev** [comment]
@bfussell, well, I think conceptually operationSuccess is just a different name/term for the same thing. However, the term operation is not really defined in the schemes we have, although the word operation, as it used in some of the specs (e.g symmetric), loosely implies a much larger scope than an individual test outcome. Given that the reporting of results is on a per tcID-basis (i.e. test case ID), I think a name containing 'test' is more appropriate. 

Anyway, I don't really care what the name is as long as we adopt a boolean value.
