### ISSUE TITLE
RSA: add support for 4096 bit keygen/siggen/sigver

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#273]
RSA keygen / siggen / sigver test vector generation fails when 4096 bits are requested.

**Comment by iabent** [comment]
I see this was added to the "Far Horizons" Milestone, but was there any eta for when it will be added? With 186-2 being phased out at EOY this will need to be tested for a quick transition. Thank you!

**Comment by celic** [comment]
As 186-5 is coming out soon, it will be a part of that set of testing. 

With 186-2 phasing out soon, we will likely add 4096 to the current 186-4 testing as well. 

This is in active development.

**Comment by iabent** [comment]
It is understood that the testing for 186-4 will be coming but I was looking more for an estimate of when vendors could expect it to arrive. 

From G.18 of the IG, “Effective on January 1, 2020, the CAVP/ACVP will stop validation testing to all other provisions of FIPS 186-2. On that date, the CMVP will place all modules which list the FIPS 186-2 algorithm certificates that include any FIPS 186-2 testing besides that of the digital signature verification on the Historical list.” As a vendor with many impacted certificates we want to begin work on making sure none/very few of them make it to the Historical list come the 1st of January, which is coming up quickly. 

Also in G.18 of the IG, “In advance of this transition, the CAVP/ACTP will make available a FIPS 186-4 compliance test for the RSA signature generation algorithm that uses the modulus size of 4096 bits.”  Can vendors be made aware of when “in advance” is, as we believe a ~4.5 month “transition before enforcement” should be minimum since IG G.18 was originally published in mid August.  We believe this to only be fair to those who intend to comply to 186-4 but cannot due to a lack of available testing support.

**Comment by celic** [comment]
We plan on making it available before the end of October.

**Comment by iabent** [comment]
Thank you, with that in mind is there any consideration extending the transition date out by 2 months?

**Comment by celic** [comment]
@iabent we are currently working on adding this in. We do not plan on extending the transition. You may test your client on the demo server with other key sizes. The properties exchanged will be the same. If you have any questions on this, feel free to send an email to Tim Hall (timothy.hall [at] nist.gov).

**Comment by celic** [comment]
@iabent, @smuellerDD This has been deployed to demo. Test away. We will move this over to prod if everything goes well.

**Comment by smuellerDD** [comment]
Am Donnerstag, 26. September 2019, 16:44:25 CEST schrieb Chris Celi:

Hi Chris,

> @iabent, @smuellerDD This has been deployed to demo. Test away. We will move
> this over to prod if everything goes well.

RSA keygen and RSA siggen worked, I get passing results.

But for RSA sigver, I do not get any data - I am just waiting indefinitely.

But something must have been broken on the ACVP server, I have a number of 
vector requests that the ACVP server failed.

        Vector set ID 59613 =============        ----------------     
UNVERIFIED
        Vector set ID 59595 =============        ----------------     
UNVERIFIED
        Vector set ID 59620 =============        ----------------     
UNVERIFIED
        Vector set ID 59597 =============        ----------------     
UNVERIFIED
        Vector set ID 59579 =============        ----------------     
UNVERIFIED
        Vector set ID 59585 =============        ----------------     
UNVERIFIED
        Vector set ID 59616 =============        ----------------     
UNVERIFIED
        Vector set ID 59599 =============        ----------------     
UNVERIFIED
        Vector set ID 59609 =============        ----------------     
UNVERIFIED
        Vector set ID 59604 =============        ----------------     
UNVERIFIED
        Vector set ID 59614 =============        ----------------     
UNVERIFIED

Ciao
Stephan

**Comment by celic** [comment]
It is not an error with RSA SigVer. From the back end, our cluster service was overwhelmed. This is a problem we have been seeing more frequently of late and are looking into a fix.
