### ISSUE TITLE
CTR DRBG: test vectors without PR seem wrong

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#395]
I get the following vectors for predictionresistance == false:

```
    "testType" : "AFT",
    "mode" : "AES-128",
    "derFunc" : true,
    "predResistance" : false,
    "entropyInputLen" : 128,
    "reSeed" : true,
    "nonceLen" : 64,
    "persoStringLen" : 0,
    "additionalInputLen" : 0,
    "returnedBitsLen" : 512,
    "tests" : [ {
      "tcId" : 1,
      "entropyInput" : "CAED3A22E6CEF0801CB84C393CAD1B10",
      "nonce" : "214AC39FACDA5E84",
      "persoString" : "",
      "otherInput" : [ {
        "additionalInput" : "",
        "entropyInput" : "5DBF858FCF24267F3C1CBFD2B3CAF805"
      }, {
        "additionalInput" : "",
        "entropyInput" : ""
      }, {
        "additionalInput" : "",
        "entropyInput" : ""
      } ]
    }, {
```
The providing of otherInput seems wrong as we do not have prediction resistance. Besides, there are 3 entries in otherInput.

**Comment by celic** [comment]
Just to confirm, the otherInput is not used when prediction resistance is not enabled?

**Comment by smuellerDD** [comment]
Am Donnerstag, 21. Juni 2018, 20:21:38 CEST schrieb Chris Celi:

Hi Chris,

> Just to confirm, the otherInput is not used when prediction resistance is
> not enabled?

Here is the DRBG test definition:

 For cases with prediction resistance enabled, each trial consists
of (1) instantiate drbg, (2) generate ReturnedBitsLen random bits, do not 
print (3) generate
ReturnedBitsLen random bits, print out (4) uninstantiate.

==> Before each generate, the entropy / additional info must be added.

For test cases without prediction resistance, each trial consists of (1) 
instantiate drbg, (2)
generate ReturnedBitsLen random bits, do not print (3) reseed, (4) generate
ReturnedBitsLen random bits, print out (5) uninstantiate.

==> the reseed implies that entropy / additional info must be added.

The test vector now contains 3 entries in otherInfo. So, I would rather think 
that for PR=false and reseed=true, otherInput should have 1 entry (i.e. the 
reseed entropy/addtl info).

Please see the DRBG CAVS spec section 6.2 for the different options and input 
data.

Ciao
Stephan

**Comment by celic** [comment]
Ah so the issue is more of the fact that there are empty values being printed when they should be omitted. Thanks for the clarification.

**Comment by atvassilev** [comment]
I think the examples in the DRBG spec follow the output data from CAVS pretty closely, in terms of the types of tests performed and the corresponding input data for them. @smuellerDD,  are you saying that the examples are bad or missing for the test case you have?

**Comment by smuellerDD** [comment]
Am Donnerstag, 21. Juni 2018, 21:39:41 CEST schrieb Apostol Vassilev:

Hi Apostol,

> I think the examples in the DRBG spec follow the output data from CAVS
> pretty closely, in terms of the types of tests performed and the
> corresponding input data for them. @smuellerDD,  are you saying that the
> examples are bad or missing for the test case you have?

The old CAVS tool uses EntropyInputReseed for reseed entropy and EntropyInput 
for PR entropy. Similarly for addtl. info.

What I am saying is that the ACVP vectors do not clearly state what entropy/
addtl input is to be used for reseed and what for PR.

Ciao
Stephan

**Comment by atvassilev** [comment]
OK, I see.

**Comment by atvassilev** [comment]
In the older versions of the spec there were explicit parameters that referred to the input for Prediction Resistance and Reseed. I guess this got lost as the spec was refactored. I see a couple of different approaches for fixing this.

1. Add an explicit string attribute intendedUse in otherInput to indicate the intended use, e.g., when PredictionResistnce is off, one can indicate that the data for reseed.

```
"otherInput" : [
                               "intendedUse" : "reSeed",
                               { "additionalInput": "95b082d603393b2207975607ac6b6472bd458c5d3d4727e1e92ebc031130231d",
                                "entropyInput": "2e92955b17e7e76fc75a478ba88f5f5b805c42945cbbcf8c669b1996c52ae3af"},
                               {"additionalInput" : "ddfa41eb363d76e3943689a13d31ebd38408f26d51a83289e3d52c2081b96ad0",
                                "entropyInput" : ""},
                               {"additionalInput" : "edb884991dd2507de07647901b8880d9db48b0f07d90a9ca8cb399581fa4dd55",
                                "entropyInput" : ""}
                            ]
```
Alternatively,
```
                          "otherInput" : [
                               "intendedUse" : "predResistance",
                               {"additionalInput": "",
                                "entropyInput": "4852aed7c47fd305aa680a6557d2f6e4112342a04eb91ed9f843671d0673cecd"},
                               {"additionalInput" : "",
                                "entropyInput" : "8b8a35a12e2d112685258742a9ad81931595fb06a7443329317e4eab9814e888"}
                            ]
```
2. Deduce the intended use from the values of the boolean properties predResistance and reSeed in testGroups.  For example, if predResistance is true, otherInput should be used as Prediction Resistance input, otherwise it should be used as re-seed input. I think this is true but let me know if have a counterexample. This would require some additional verbiage be added to the spec to explain this implicit assumption so people don't get confused. 

Thoughts, comments?

**Comment by smuellerDD** [comment]
I would be against both options because this breaks the concept of JSON: two keywords at the same hierarchy level have dependencies where they only together can be interpreted. This would make a generic parser that does not interprets data hard or impossible.

Why not using a keyword otherInputReseed and otherInputPr that have the entropy and addtl data for the respective use case?

Cui bono?

**Comment by atvassilev** [comment]
My recollection is that the explicit naming of otherInput got nixed because of too many properties floating around. 

I am not sure I buy your argument against #2. You can generically parse the data in the JSON test vector as is. It is when you are ready to pass the data to the native API where you have to decide how to feed it in. You have to know what tests belong to what test group anyway. The test group specifies a number of common for all these tests parameters, including the configuration settings of reseeding and prediction resistance.

**Comment by smuellerDD** [comment]
Yes, it is possible the way you describe. However, I am not sure why such additional keyword should be introduced when the keyword for the entropy data could be made clear enough. Is there a technical reason why the keyword otherInput must remain and cannot be replaced with two other keywords?

**Comment by Kritner** [comment]
Was there a consensus on this?  I believe the idea behind `otherInfo` was that it would always be involved with `Reseed` and `Generate` DRBG functions.  Reseed is always the first index when there are 3 entries.  I can see how this could be weird to forward the same object values to separate functions...

would it make more sense to just have the `otherInfo` object contain `additionalInput`/`entropyInput` specifically for the `Generate` function?

The `ReseedAdditionalInput` and `ReseedEntropyInput` could be pulled out of `otherInfo` and put into a more parent property - this seems to make more sense since a reseed will only be done a maximum of once per test case, where generates will always be done twice.

Thoughts?

**Comment by Kritner** [comment]
Deployed to demo
