### ISSUE TITLE
Protocol Spec updates

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#443]
@hbooth With the addition of the new URIs for V0.5, what should we be using for authorization flow after sending to /login ? The spec currently still has /register in sections 11.1.1 and 11.1.2.

Almost seems like the next POST could be one of several different options.

**Comment by bfussell** [comment]
@celic @hbooth @atvassilev 
Anyone want to take a stab at this ?

**Comment by atvassilev** [comment]
@bfussell, good question, here is my take. I think it makes sense to use the access token returned from /login because for most/all of the new URIs the context is not a single session, which is the case for the token returned by /register. Moreover, one does not need to register any capabilities to access and use the data returned from the new URIs. Also, I do not see the need to create a new token for accessing the new URIs if the access token from /login can do the job.    

I think the flows in Section 11.1.1 and 11.1.2 precede the introduction of the new URIs and need to be updated to cover these use cases.
