### ISSUE TITLE
Ensure all documents describe "deferred" usage if needed

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#444]
Some algorithms use `deferred` to describe when a client should provide more information than just the output to a function. The server would need the input along with the output in order to perform the validation.

It has been brought up that `deferred` isn't described in several specifications that use it. They need to be updated to describe what `deferred` means in the validation process... 

Part of this issue is that the validation process isn't described in the specifications yet. Without that context, it can be hard to understand why a `deferred` property is used.

**Comment by celic** [comment]
#440 is relevant here.

**Comment by atvassilev** [comment]
@celic thanks for the additional light on this issue. I think this changes the balance related to the choice between that original term and the new one borrowed from the RSA registration parameters. What confused me before in responding to #440 was that deferred is not even mentioned in the RSA spec - anywhere at all, including the examples. Without context, the term from Registration seemed much more self-explanatory. 

In fact any term would be fine, provided it is defined and explained properly, like I said in my response to #440.

Given that deferred is used in several places, I now think that deferred is ok to use everywhere but it must be defined and explained in all specifications that use it.  Correspondingly, PR #442  should revert to using deferred but keep the useful information in the text explaining it.

**Comment by Kritner** [comment]
Just to make sure I'm understanding - we want to describe `deferred` when it can apply to a test case, regardless of whether or not we're actually sending that value to the IUT along with the vector set?

I had assumed we weren't ever sending this value, unless by mistake.

**Comment by atvassilev** [comment]
@Kritner, well my understanding is that we are sending "deferred" without describing it in some cases, like the RSA spec. 

To the broader point you are raising, if we have a test case that fits the "deferred" paradigm, i.e. the client does most of the work and sends back to the server some intermediate results so that the server can verify it all, we have to describe this testing scenario in the specification and use consistent JSON properties in the schema to exchange the data. This would mean that you would use "deferred" as the property of the test cases when the server sends a test vector to a client in the deferred test scenario.  

I hope this makes sense and let me know if you would like to discuss this out-of-band.
