### ISSUE TITLE
v0.5: KAS ECC/FFC spurious errors

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#481]
For KAS ECC / FFC, the ACVP flags some validation responses as errors. Though it does not give any real good answers why it marks it as failure. 

I am debugging this issue with the vendor, but we are stuck and do not see any apparent issue. Also, the IUT implements the key check as per SP800-56A 5.6 that was discussed in other bug reports.

Could you give us some hint about why the ACVP server thinks our answers are wrong? The IUT is OpenSSL.

vsID 123 and 124 for example.

Thanks a lot.

**Comment by Kritner** [comment]
Hey @smuellerDD unfortunately I don't have enough information recorded in our internal information for these vector sets to determine why the answers were flagged as failure.  I am making an update for the next release to include the reasoning behind why we would be expecting a failure.

**Comment by smuellerDD** [comment]
Am Dienstag, 6. November 2018, 16:39:29 CET schrieb Russ Hammett:

Hi Russ,

Thanks a lot! The reason why I ask for help is that the KAS tests all passed 
before and now show errors. And on my end, I am at a loss why they are 
failing.

Ciao
Stephan

**Comment by Kritner** [comment]
Working through testing of an internal fix now.

A few changes that are going through:
* The updates will now include a reason we were expecting a specific test case to fail in the validation file.  
* The failure reason will be stored in our own internal representation of the vector set, so we can go back and look at why a test case should have failed
* Update to ensure we're only injecting key failure types on schemes that actually use that key type.
* Updated so that an assurance function is **not** required.  Previously it was required the IUT to provide at least one assurance, but these assurances are related to EC/DSA, which is not even necessarily a prerequisite of the algorithm validation.

Will update once this chance makes it out to demo

**Comment by Kritner** [comment]
This update was deployed to demo.

**Comment by smuellerDD** [comment]
The ACVP server says:

```
  }, {
    "tcId" : 24,
    "result" : "failed",
    "reason" : "Incorrect TestPassed result. Test expectation: \"Failure - IUT should calculate different tag due to Z value changed.\""
  }, {
```

Same error for tcId 38, 60, 61

vsID 70.

The original test response was generated with OpenSSL. Now, I regenerated the response with GnuTLS. Both, OpenSSL and GnuTLS create the very same responses. I.e. both IUTs calculate the same data.

I am puzzled that the ACVP server does not like it.

Note, both have (a hopefully correct implementation of) SP80-56A section 5.6 compliant key check.

**Comment by Kritner** [comment]
Thanks @smuellerDD, I'll dig in and see what I can find.  At least I now know where abouts to look! :)

**Comment by Kritner** [comment]
@smuellerDD I've found an issue on our end related to these test failures, should have a fix in with the next push.

**Comment by elliemdaw** [comment]
I am seeing these errors too... have they been pushed out yet? Looks like your comment was 8 days ago, but the error still shows up. Thanks!

**Comment by Kritner** [comment]
A deploy has not made it out to demo yet, sorry for the delay.  Hoping we'll be getting one out soon.

**Comment by elliemdaw** [comment]
No worries, just making sure I hadn't missed something! Thanks!

**Comment by elliemdaw** [comment]
It's working for me now! Thanks!

**Comment by smuellerDD** [comment]
confirmed, working
