### ISSUE TITLE
ECDSA curves case sensitivity

### ISSUE THREAD

**Issue by elliemdaw** [usnistgov/ACVP#484]
When registering curves the following error shows:

"error" : "Property value(p-224) for (curve) in Algorithm (ECDSA (keyGen)) is not valid. Validation: (Values must be one of: P-224, P-256, P-384, P-521, B-233, B-283, B-409, B-571, K-233, K-283, K-409, K-571)"

Not a big deal and I can fix this on our end for now of course, but might be good moving forward to have the server be case insensitive for curve names?

Thanks!

**Comment by celic** [comment]
As long as all JSON is case sensitive, we will be trying to match up anything that appears in a NIST specification exactly. Curve names are capitalized. I understand the frustration of failing a test because the capitalization changed. Ideally all of these properties could be case insensitive, but that is not the intention of the server at the moment.
