### ISSUE TITLE
v0.5: Allow sample to be obtained at any stage in a vsID lifecycle

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#518]
It happens commonly that sample vectors are requested after the test vectors are downloaded or even test responses are uploaded (and verdicts are obtained). This usually happens when something fails and one wants to compare with the expected results.

Currently, the ACVP server rejects any sample request that is not made at the time of fetching the test vectors with the following result:

```
{
  "acvVersion" : "0.4",
  "error" : "vectorSetId (2981) found but answers were not requested during generation"
}
```

I would like to request the following feature enhancement: Allow the gathering of samples at any stage of an ACVP vsID, provided that the finalizing PUT operation to obtain a certificate is not sent.

**Comment by celic** [comment]
I'm not sure if this is possible in every situation. 

Consider a Signature Generation vector set. The client registers without sample, and receives back essentially an empty prompt.json containing only `tcId`s and `message`s. The client generates a bunch of signatures and provides the public key corresponding to the private key used to generate those signatures. The server then runs a Signature Verification procedure using the public key and the signature.

There is no way for the server to switch the vector set into a sample set as it does not possess the client's private key. The expected behavior for a sample in this case would have the server generate a key pair at the same time as generating the random `message`s and signing them before the client. I don't believe there is a way for the client to input their own key into this set-up. 

Some of these struggles might be alleviated with the `expected` field in the `validation.json`. This would be much easier to fit into the workflow. After receiving an unsatisfactory `validation.json`, perhaps the client could request the `expected` values which would essentially just run the same validation step but provide those json fields. In the back-end, the `expected` values are not provided by default and are not accessible via the workflow (as of now I believe). Obviously now that the work putting them in place has been completed, they should be accessible in some manner and I think this solves the use-case you are asking for with the `sample` flag.

**Comment by Kritner** [comment]
While not exactly what is being asked for in this issue, https://github.com/usnistgov/ACVP/issues/280 should be *pretty close* especially when coupled with @celic's response https://github.com/usnistgov/ACVP/issues/518#issuecomment-460410051
