### ISSUE TITLE
Hash Protocol Specification

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#53]
Is anybody working on getting together a specification for hashing algorithms? This should be separate from the already included HMAC protocol.

If this hasn't been started yet, I can begin work on it. Otherwise, if someone has begun work on the document I can contribute to make sure it matches the server's expectations.

**Comment by bfussell** [comment]
All of the hashing algorithms should be covered in acvp_sub_hashmac.xml including
SHA1, SHA2, SHA3, SHAKE, HMAC and CMAC.  There are no examples yet for SHA3
or SHAKE, but all the others have at least a simple example.

Or are you referring to something not in that spec ?

Regards,

Barry

**Comment by celic** [comment]
I think these should be separated into separate documents. Hash algorithms are used in more than just HMAC and are often validated on their own. I would prefer if we defined a protocol for the various SHAs and then referenced that document as needed for HMAC.

**Comment by bfussell** [comment]
We grouped a few of the algorithms together specifically to reduce the total
number of specs.  For example, for TDES and AES we consolidated the
CAVP docs AESAVS, TMOVS, CCMVS, GMAVS, KWVS and XTSVS into the
acvp_sub_symmetric.xml spec.  Simply because hash and mac algorithms are
in the same spec doesn’t mean they have to be validated together it simply
means they were similar enough in format that creating separate specs
wasn’t warranted.  I think that is represented in the spec fairly well, however
if you think that needs to be spelled out better we could add some verbiage to
explain that.

**Comment by celic** [comment]
In the document under 2.1 HASH Algorithm Capabilities Registration, there is the property "inEmpty" which has the description "Implementation does not accept Null (zero-length) messages." Can we change this description to match the name of the property? "inEmpty" should refer to "Implementation does accept Null (zero-length) messages."

**Comment by bfussell** [comment]
Sounds good to me.

**Comment by celic** [comment]
Back to the original issue matter, I spoke to Sharon Keller (the current program director of CAVS) about the design of CAVS and why certain decisions were made. While ACVP is a new platform, it would serve us well to learn from previous design choices. One thing she was insistent on was the one-to-one nature of the CAVS tool. Each tab on the program corresponded to a specific FIPS document which then corresponded to a specific Algorithm Validation System document. 

For example, if I look at SHA3, it is under [FIPS 202](http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf) as a single document as well as [SHA3VS](http://csrc.nist.gov/groups/STM/cavp/documents/sha3/sha3vs.pdf) as a single document explaining the validation procedure and tests. 

In my mind this structure is ideal as it allows quick retrieval of the specific information. I am preparing the XML documents for SHA1/2 [FIPS 180](http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf) and for SHA3/SHAKE (FIPS 202). As well I am editing the HMAC XML document to remove information about the hashing algorithms. 

It should also be noted that SHA1/2 and SHA3/SHAKE will be separate documents as they require different parameter sets. Rather than outline the different parameters in one large table, it makes sense to break up this information so someone can find the information to validate a specific algorithm in a document that is entirely relevant to their needs. This allows us to include more detailed examples for each algorithm with less of a worry on file length or organization.

**Comment by bfussell** [comment]
I don't see it as a priority since we're focusing on implementation at this stage and fixing functional things, but if you have the cycles and your team feels like that is more important....  Your current pull request, #58,  has a bunch of the changes associated with this issue - was that intended ?  There's some typos in  sha and sha3 and it looks like hashmac spec still needs some of the SHA stuff removed.

**Comment by atvassilev** [comment]
Chris, it is good that you have consulted with Sharon to understand the previous design choices. While this may explain the architecture decisions about the CAVS tool, it does not mean the same approach is the best for ACVP. We are working with a fundamentally different approach and the algorithm specifications we create are de-facto the new validation system specifications. This means that we have the freedom to decide the best approach for this project, learning from the past but not being wedded to it. 

I personally don't find the rationale you provided as a compelling enough reason to follow the CAVP approach in this. Moreover, each particular section in the new spec may refer to the corresponding FIPS document (180, 202, etc).  

Barry and his team wanted to limit the number of specs. To give you another example, when I worked on the RSA algorithm, I also lumped together a bunch of separate RSA-related specification because the original split in CAVP did not land itself well in the new system. So, the real questions are how does the complete SHS spec look like? Is it too difficult to read and understand?  Is it going to interfere with engineers with experience in crypto to implement it correctly?

**Comment by DBugger32** [comment]
Chris's impetus was driven by the facts that
a) the SHA specs were not immediately evident in the ACAVP docs
b) SHA1/2 and SHA3 are completely different beasts
c) SHA is a basis for more than MAC

Discovery is an important part of any protocol, and the fact that a
fundamental algorithm was not evident in the specs suggests it would be a
point of confusion for people going forward, especially to those not
intimate with the project.

Don't see any advantage to having "fewer" spec documents if they are
longer, more complicated, and less clear.  Breaking out the SHA family will
make it easier for discovery, breaking out SHA1/2 and SHA3 will make
implementation easier as developers will not have to guess which parameters
are meaningful for which flavor of SHA.

On Thu, Feb 16, 2017 at 11:08 AM, Apostol Vassilev <notifications@github.com

**Comment by celic** [comment]
Closed with #58
