### ISSUE TITLE
Authentication errors appear again

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#530]
Lately, authentication errors appear again once in a while:

```
{
  "acvVersion" : "0.4",
  "error" : "The supplied one time password could not be verified"
}
```

Unlike previously where my TOTP value discarded leading zeros, this time the ACVP server complains about TOTP values which have full 8 digits.

I am unaware that I modified anything in my TOTP generation.

At the time of writing, every authentication request fails. The first errors started to appear about at the beginning of this week, very rarely.

**Comment by bfussell** [comment]
I've seen that as well over the last couple of days.  Thought it may be my server that had drift issues.

**Comment by hbooth** [comment]
I took a look at this last night and it appears, that it is our server with the drift issues. Our SA is out this week but when he returns next week I will have him take a look. There appears to be some misconfiguration with the time server settings. I hand-updated the time to something closer to the official time, hopefully it will stick long enough for us to figure out what the issue is and get the time set-up correctly again.

**Comment by hbooth** [comment]
Our SA reconfigured our NTP configuration and hopefully this issue has been resolved.
