### ISSUE TITLE
SHAKE: outLength definition

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#580]
The spec defines "outLength" as the keyword. Using that, the server replies

```
{
  "acvVersion" : "0.5",
  "error" : "Incorrectly formatted JSON (1:263): expected field name was not provided: outputLength"
}
```

So, I changed it to outputLength (i.e. the spec seems to be needing an update).

The spec defines the outLength value to be a domain. When I use the absolute integer definition for the domain, the server returns an error. For example, I use the following:

```
  {
    "isSample":false,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "algorithms":[
      {
        "algorithm":"SHAKE-128",
        "inBit":false,
        "inEmpty":true,
        "outBit":false,
        "outputLength":[
          64,
          128,
          256,
          512
        ]
      },
      {
        "algorithm":"SHAKE-256",
        "inBit":false,
        "inEmpty":true,
        "outBit":false,
        "outputLength":[
          64,
          128,
          256,
          512
        ]
      }
    ]
  }
]
```

The server returns:

```
{
  "acvVersion" : "0.5",
  "error" : "Invalid JSON input (1:266): Expected Start Object not found."
}
```

**Comment by Kritner** [comment]
@smuellerDD it looks like the spec needs updating for the registration to `outputLength` rather than `outLength`.

I'm not sure if it was intentional that the registration's `outputLength` and vector's `outLength` differ in their property names, but that is how things are at least currently.

As far as your issue with "Expected Start Object not found" - it seems that shake is expecting a domain in a single domain segment.  I'm not sure on the specifics of this algorithm, and why it would be expecting only a single segment rather than complete domain, but maybe @celic recalls?

Hopefully "single domain segment" makes sense, but just in case:

Invalid due to having multiple segments:
```
"outputLength": [8, 16]
```

Valid single segment:
```
"outputLength": [{"min": 8, "max": 16: "increment": 8}]
```

**Comment by celic** [comment]
That is correct Russ... There is some awkwardness in SHAKE such that the
output length requires just a single domain segment and nothing more. The
MCTs are poorly designed (as a test not the code) for handling varied min
and Max lengths and even less so for stagnated domains. This needs to be
revisited in the future.

**Comment by celic** [comment]
I merged the PR. Feel free to close if solved.

**Comment by smuellerDD** [comment]
Confirmed, working.
