### ISSUE TITLE
Terminology Section: Request and Response keywords

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#585]
I have some misgivings regarding the use of `Request` and `Response` within the terminology section and giving them ACVP specific definitions. These two terms already have meaning at the HTTP layer and we (especially me) have used these terms to indicate HTTP Request and HTTP Response definitions when describing the various resource operations. I believe we were using different terminology earlier that intentionally tried to avoid this sort of overloading. If the prior terms were not acceptable could we use something that does not overlap with already commonly used terms?

**Comment by smuellerDD** [comment]
Am Sonntag, 31. März 2019, 04:09:26 CEST schrieb Harold Booth:

Hi Harold,

> I have some misgivings regarding the use of `Request` and 'Response` within
> the terminology section and giving them ACVP specific definitions. These
> two terms already have meaning at the HTTP layer and we (especially me)
> have used these terms to indicate HTTP Request and HTTP Response
> definitions when describing the various resource operations. I believe we
> were using different terminology earlier that intentionally tried to avoid
> this sort of overloading. If the prior terms were not acceptable could we
> use something that does not overlap with already commonly used terms?

Well, we have various types of requests and respones so I think you are 
perfectly right.

I think what is referenced as request is the test vector retrieval and test 
result submission.

The test vector retrieval consists of the HTTP POST for registering a cipher 
definition and the HTTP GET for the testvector download.

The test result submission consists of the HTTP POST for the test result 
upload and HTTP GET for the test verdict download.

Ciao
Stephan

**Comment by bfussell** [comment]
I think this can all be solved by updating the terminology to include the HTTP layer operation that is occurring. Then any use of request or response or submission is understood to include HTTP and in many of the cases ACVP components(JSON) as well.

I agree 'test results submission' is a better description of what is happening. It is less of a simple response. We should have 2 submission types for ACVP in the terminology section. Registration/Capabilities Submission and Test Results Submission.

Registration/Capabilities Submission - An HTTP POST requesting an operation at the server. It includes JSON specifying details about the request, such as vendor information when creating a new vendor in the database.

Test Results Submission - An HTTP POST used for submitting test results. It carries JSON that provides test results specific to an individual test vector.

Retrieval Request - An HTTP GET requesting retrieval of data from the server.  The URL contains specific context about the request such as the ID of the test vector set requested.

From my perspective it looks like we should change some of the 'response' usage to 'submission', but for the most part the usage of request can stay as is since it is cleared up in the terminology.

**Comment by dmchodnicki** [comment]
Existing Request/Response terminology has not been proven to be a source of confusion.  Item is being Closed as no longer required.
