### ISSUE TITLE
Many of the links in the status table are broken because of file name changes

### ISSUE THREAD

**Issue by acronymhaterheidi** [usnistgov/ACVP#593]
accidentally posted comment, not needed

**Comment by hbooth** [comment]
Should this issue be closed?

**Comment by acronymhaterheidi** [comment]
The issue is legitimate, I accidentally commented the default bug reporting info and was not able to delete the comment. Probably not the best wording

**Comment by hbooth** [comment]
Which status table and where? Not 100% sure of the context of the issue.

**Comment by acronymhaterheidi** [comment]
I am referring to the status table in the README. For example, all of the block cipher modes, hash functions, and the 135 KDFs are dead links

**Comment by Kritner** [comment]
This is due to many of the specs being renamed to "draft", do we know what the timeframe of that will be?  If it's going to be for a decent period of time then the readme could be updated with the new draft file names.  If not, it may be ok to just wait until the drafts are no longer drafts (at which point their file names may be changing either way?)

**Comment by atvassilev** [comment]
Just fixed the broken URL's. Let us know if you spot any remaining problems.

**Comment by acronymhaterheidi** [comment]
It looks like the hash functions and block ciphers are fixed, but the 135 KDFs are still broken.

**Comment by atvassilev** [comment]
Just fixed the KDF's. Thanks for pointing them out.
