### ISSUE TITLE
/dependencies SPEC

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#603]
Section 11.12.3 contains "dataType" - shouldn't that reference be "type" as currently being accepted? Also, shouldn't there be an exhaustive list as this type defines which additional fields are to be used?

11.12.3: What is expected with the field "description"? Isn't the definition of the dependency already unambiguous?

11.12.3: dataTypes: currently we have software and processor - shouldn't that be synced up with the terminology of FIPS (software, firmware, firmware-hybrid, hardware, ...)?

**Comment by hbooth** [comment]
The `List Dependency Properties` (currently 11.12.3) portion of the spec is not fully-baked. It's still not clear exactly what we need here yet. I am hoping the work ongoing in the several CMUF WGs will help to better define what we need, or further research here at NIST will progress on how to structure and represent this data. Consider this section a placeholder. We don't currently implement this endpoint and we don't expect clients to use it at this time either. Once we have a better idea of the requirements around this we will tighten things down on the dependencies, but until then the name/value pairs that can be used on a dependency is unbounded and is at the discretion of the creator of the dependency as to what properties are needed to fully define/describe the dependency.

That said:
> Section 11.12.3 contains "dataType" - shouldn't that reference be "type" as currently being accepted? Also, shouldn't there be an exhaustive list as this type defines which additional fields are to be used?

No, `dataType` describes what the type for the value of a dependency property. Yes, the spec should define an exhaustive list for the type. Something like `string, number, boolean` would likely be sufficient.

> 11.12.3: What is expected with the field "description"? Isn't the definition of the dependency already unambiguous?

  This is intended to provide a description of the dependency property to server as a documentation of sort so that anyone who uses it would know when and how to use the property.

> 11.12.3: dataTypes: currently we have software and processor - shouldn't that be synced up with the terminology of FIPS (software, firmware, firmware-hybrid, hardware, ...)?

See my response above.

Addendum: So I wrote the above and as I reviewing it I realized that you may have intended to ask questions about Section 11.12 where the dependency properties are described. I will go back and add some additional detail for those properties since they are currently rather sparse.

**Comment by hbooth** [comment]
PR #604 adds additional detail to help clarify what a dependency is and what is expected.

**Comment by smuellerDD** [comment]
Am Donnerstag, 4. April 2019, 15:09:17 CEST schrieb Harold Booth:

Hi Harold,

> The `List Dependency Properties` (currently 11.12.3) portion of the spec is
> not fully-baked. It's still not clear exactly what we need here yet. I am
> hoping the work ongoing in the several CMUF WGs will help to better define
> what we need, or further research here at NIST will progress on how to
> structure and represent this data. Consider this section a placeholder. We
> don't currently implement this endpoint and we don't expect clients to use
> it at this time either. Once we have a better idea of the requirements
> around this we will tighten things down on the dependencies, but until then
> the name/value pairs that can be used on a dependency is unbounded and is
> at the discretion of the creator of the dependency as to what properties
> are needed to fully define/describe the dependency.

Currently I see:

- the description field is required by the ACVP server

- I added a "features" field with an array of CPU features which was not 
accepted by the server


> That said:
> > Section 11.12.3 contains "dataType" - shouldn't that reference be "type"
> > as currently being accepted? Also, shouldn't there be an exhaustive list
> > as this type defines which additional fields are to be used?
> No, `dataType` describes what the type for the value of a dependency
> property. Yes, the spec should define an exhaustive list for the type.
> Something like `string, number, boolean` would likely be sufficient.

I see.

> > 11.12.3: What is expected with the field "description"? Isn't the
> > definition of the dependency already unambiguous?
>   This is intended to provide a description of the dependency property to
> server as a documentation of sort so that anyone who uses it would know
> when and how to use the property.

Ok, the reason I ask is because when I POST some data it requires me to 
provide a field "description".

> > 11.12.3: dataTypes: currently we have software and processor - shouldn't
> > that be synced up with the terminology of FIPS (software, firmware,
> > firmware-hybrid, hardware, ...)?
> See my response above.
> 
> Addendum: So I wrote the above and as I reviewing it I realized that you may
> have intended to ask questions about Section 11.12 where the dependency
> properties are described. I will go back and add some additional detail for
> those properties since they are currently rather sparse.

Thank you, that is good.

Though, do I infer from your statements the following:

- in order for a product to be certified and the /module entry to be defined, 
it needs an oe-ID

- to create an oe-ID I infer that I can simply add an OE definition *without* 
any dependency-IDs (for now)




Ciao
Stephan

**Comment by hbooth** [comment]
As we discussed, dependency items are needed to fully describe the OE. Hopefully, the updates to the spec will assist others moving forward.
