### ISSUE TITLE
Suggestion: "Range" object utilized in spec

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP#67]
Some algorithms may benefit from beginning to use a `range` object that allows for the specifying of a `min` and `max` value that is allowed for the parameter.

AES-CCM and SHAKE specifically use a range of values that are entered.  If 0 min and 32 max are entered in the case of AES-CCM, all values between 0 and 32 are tested.  A random sampling of values within the range is also feasible.

AES-GCM could also use this range object, as currently the `aadLen` array accepts up to 5 values, one can be a 0, 2 can be divisible by 128, and 2 are not divisible by 128.  AES-GCM could begin accepting a min and max, and a separate flag for `supportsNonBlockBoundryAadLen` or similar.

This `range` value will potentially lead to a few new parameters, but should make things a bit more explicit, and hopefully easier to understand.

Example of current registration for AES-GCM:

```
{
	"aadLen": [0, 128, 256, 120, 248]
}
```

could become:

```
{
	"aadLen": {
		"min": 0,
		"max": 256
	},
	"supportsNonBlockBoundryAadLen": true
}
```

Thoughts?

**Comment by celic** [comment]
This would be useful for SHAKE as well, which requires a range of valid sizes for digests.

**Comment by bfussell** [comment]
I agree the min/max range would be an improvement.

**Comment by atvassilev** [comment]
I also like this but think we need to specify also an increment to define it well, provided the entries in the range are equally distant.

**Comment by Kritner** [comment]
Just started a PR #71 

@atvassilev I like the idea of the increment, but could you elaborate on it a bit more?  The use cases I'm seeing currently, are always either an increment of 1, or variable increment.

In AES-CCMs case, we could have 0-65536, where we'd have a 1 increment from 0-32, and then a large jump to the 65536 value.

In AES-GCMs case, we can accept values 0-65536, and the values are always mod 8, but can be either mod 128, or not 128.  In this case, we'd likely just want to randomly select values to test with within the range, that are either mod 128 or not mod 128, depending on the options of the capabilities registration.

@celic I did not make updates to SHAKE as it seems like there's an active PR out for that one #58

**Comment by atvassilev** [comment]
@Kritner when you specify a range for a particular parameter values you need to define the beginning, the end and the increment to get to the intermediate values, unless there is some external agreement about it. For example, if the range of supported RSA keys is from 1024 to 4096 bits then what is the actual set of supported keys? Well the answer depends on the increment: in one case, with increment 512 bits, the set is 1024, 1536, 2048, 2560, 3072, 3596, 4096. With a 1024 increment, the set is 1024, 2048, 3072, 4096. Technically speaking, both increments make sense so one needs the specify it explicitly. So, this could become 

"rsaKeyRange" :  { 
                          "min" : 1024,
                          "max": 4096,
                          "step": 1024
                          }

In your example, the situation is more difficult because if you say 

{
	"aadLen": {
		"min": 0,
		"max": 256
	},
	"supportsNonBlockBoundryAadLen": true
}
it is not clear at all what the acceptable values are apart from the end points of the range 0 and 256. In your case I think it is more appropriate to have an array of acceptable values since they are not equally spaced.

**Comment by Kritner** [comment]
Ah, I see what you mean.  

In CCMs case, if `min: 0, max: 32` is specified, each value would be used 0, 1, 2, 3, 4, etc...

That does not seem to be the case with GCM, but I'm not sure the current wording works especially intuitively either.

> Array to include, if supported,  zero, two values divisible by 128 and two values not divisible by 128

Based on talking with others, it seems the point of taking "mod 128" and "not mod 128" values, indicates that the implementation supports "block sized" and "not block sized" lengths of an PT (or AAD).  What would the expectation be for cases where only a single value mod 128 is provided (as an example)?  Would that value be given twice? 

`"ptLen" : [ 0, 128, 128 ]`

or a single time 

`"ptLen" : [ 0, 128 ]`

?

I find both methods of depicting the lengths have their own points of potential confusion.
