### ISSUE TITLE
KAS with key confirmation macData validation issues

### ISSUE THREAD

**Issue by dghgit** [usnistgov/ACVP#679]
**testSessionId**
6609

**vsId**
20448

**Algorithm registration**
[registration.zip](https://github.com/usnistgov/ACVP/files/3420557/registration.zip)

**Endpoint in which the error is experienced**
https://[acvpUrl]/v1/testSessions/6609/vectorSets/20448 GET

**Expected behavior**
We're producing a passing response for the following test:
          {
            "staticPublicServerX": "1113E956A54B3A4AFF7720A73D4D64628293B46EA8E85EC261C430D9B3597E3E",
            "staticPublicServerY": "3368D5E06AD0A74A342B46CF62EB0D72CD089FF400B637F0568C3133ACC02A2F",
            "staticPrivateIut": "D87143741EB80CE1CEAAFDEB12574CC101015EC6B811E965BCB5360038B72EF6",
            "staticPublicIutX": "843ACC55E4148F30586F87B23C52872169E5CBF55D72EC94E942A6F566A16EEC",
            "staticPublicIutY": "026BF1CFB7353383EDBA08CA2B0EEAB208FEA4AA56F67B27563495D1C3F4E227",
            "tcId": 63,
            "nonceDkmServer": "D0FC495F31ED8D4E0F5634031D2C0372",
            "oiLen": 376,
            "oi": "434156536964D0FC495F31ED8D4E0F5634031D2C0372A1B2C3D4E59778229E5F9EFED7AD14E8CEB8B62EAAD5A9DFDC",
            "nonceAesCcm": "AD1BE72DD59458",
            "tagIut": "F10145A5B8D3A748"
          },
however the server is responding with:
{
"tcId" : 63,
"result" : "failed",
"reason" : "Incorrect TestPassed result. Test expectation: \"Failure - IUT should calculate different tag due to MacData value changed.\""
 },

The values provided with the test do result in the tag provided though. In the case of a test with the old tool, I would have expected to see a "macData" field in the record which we would have picked up instead, usually this would have been tweaked and would have resulted in the failing tag. Is the field missing in this case and should be there? Or am I missing something instead?

These are the only failures we are seeing with KAS ECC, so any help would be much appreciated. Thanks.

**Additional context**

**Comment by Kritner** [comment]
I think the intention of not including the macData is that it can be derived from other information within the test group/test case and we're trying to include less of the intermediate values to (hopefully) better ensure more thorough testing.

For a test such as the one described, the intention is that the ACVP server should be using an incorrect value for the macData, which should propagate errors through the steps that rely on that macData, that would be another part of the reasoning behind not including that information within the prompt file (we don't want to provide the *bad* data being used, and want the IUT to be able to determine that KAS was not successful).  That being said, there could be something wrong on our end related to this particular failing test type.

I will take a look at this particular set of intended failure cases, it looks like the other intentional failures made it through correctly

**Comment by Kritner** [comment]
@dghgit i've found the reasoning behind the issue on our end, a fix should be in the next deploy to demo (which is currently slated for thursday).

**Comment by Kritner** [comment]
This change has been deployed to demo. Please let us know if there are any issues.

**Comment by dghgit** [comment]
Have spent the last couple of hours testing. No longer seeing any failures due to this, looks like this now works correctly. Thanks.

**Comment by Kritner** [comment]
Good to hear, thanks!
Note that this change is not yet on prod. As long as there aren't issues for some of the other changes in this release to demo, I believe the changes can be expected on prod sometime next week.
