### ISSUE TITLE
Asymmetric ciphers: validation executable failed

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#680]
**testSessionId**
7050

**vsId**
21446, 21467, 21468, 21469, 21470

After uploading the responses, we fetch the following verdict information:

```
[ {
  "acvVersion" : "1.0"
}, {
  "results" : {
    "vsId" : 21468,
    "disposition" : "error",
    "message" : "validation executable failed for: 21468"
  }
} ]
```

So it seems to us that the verification backend cannot process the data.

**Comment by Kritner** [comment]
@smuellerDD would you be able to just submit one of the problem registrations and keep it in an uncanceled state (and let me know the vsId)? It's pretty early in the morning over here so getting a hold of someone to pull logs from the previous attempts will be difficult for at least the next few hours.

**Comment by Kritner** [comment]
@smuellerDD I see (at least in part) of what is happening. With the changes from #664, many of the previously interpreted `BigInteger`s are now being interpreted as `BitStrings`.  Our `BitStrings` have a requirement of being full byte length, but they support padding unlike `BigInteger`.  I have found at least one occurence of non byte length `BitStrings` being sent within vs 21467 see:

```json
{
      "qy" : "e3de3c63653d7170aed247094162523dabc3f9125b8b4e73e323f7f14ca1ea1",
      "qx" : "cf4e604c4c7bfc92e336dc377dbd531e01989d345a66a1f0bac57edf9128d1b4",
      "tcId" : 10,
}
```

the `qy` value is only 63 characters, rather than providing the 0 nibble as the 64th.  It seems that this would have been fine previously, as when parsing the value as a `BigInteger` on our end, there's no such thing as padding.  The `BitString`s however do require the values to be at the byte boundary.

I don't know if this is a simple change on your end or not, or if it's something we should infer on our end to pad the most significant end with a 0 if it's not at the byte boundary (which doing such a thing may have further reaching consequences that will need some evaluation and testing).

Thoughts? tagging @celic for visibility.

**Comment by smuellerDD** [comment]
Am Freitag, 26. Juli 2019, 11:53:44 CEST schrieb Russ Hammett:

Hi Russ,

Thanks for the hint - please do not change your implementation - I think we 
can fix it from our end.

Yet, may I suggest that the backend catches such non-alignments and to report 
the issue to the caller?


Ciao
Stephan

**Comment by Kritner** [comment]
Catching these issues with `BitString`s is definitely something we should be, but are not currently, doing.  I will look into some options for doing so.

Hopefully that is the extent of the problem you experienced, I have found a few other occurrences of it other vector sets from your list but have not been able to confirm that is the issue in all cases..

**Comment by Kritner** [comment]
@smuellerDD I've added an issue for tracking some enhancements to the server side for giving the clients an easier time identifying problems when encountered.  I'm not sure when this enhancement is going to be put in, but wanted to at least get something out there for tracking purposes.

Have you had a chance to do any additional testing regarding this `BigInteger` -> `BitString` change? The padding of your hex strings to be an even number should be enough to get past the first hurdle, and hopefully that is the only one!

**Comment by smuellerDD** [comment]
After fixing the answers to prepend a '0' hex-digit to the outputs of bigintegers, we re-ran on newer test vectors and submitted them to the NIST ACVP server.

All of these have been passing thereafter.

Thanks.

Shall we close the issue?

**Comment by celic** [comment]
We can close this issue and spawn a new one capturing the behavior of the server. The server should not be crashing under this circumstance. We have a fix in the works to return a proper error back to the client. But we will still require that all hex coming in to the server be represented in complete bytes (hence an even number of characters 0-F).

**Comment by Kritner** [comment]
Closing this issue since @smuellerDD is having success since passing in the even length hex strings. We have a follow up issue #685 to take on at some point in the future.
