### ISSUE TITLE
Remove obsolete large submission flows from ACVP spec 

### ISSUE THREAD

**Issue by atvassilev** [usnistgov/ACVP#683]
With the latest JBOS server update it is no longer necessary to handle large submissions as currently described in the spec. All definitions and references to this obsolete behavior have to be cleaned up: Section 9, Section 11.4 and Section 12.

**Comment by smuellerDD** [comment]
Am Dienstag, 30. Juli 2019, 15:31:38 CEST schrieb Apostol Vassilev:

Hi Apostol,

> With the latest JBOS server update it is no longer necessary to handle large
> submissions as currently described in the spec. All definitions and
> references to this obsolete behavior have to be cleaned up: Section 9,
> Section 11.4 and Section 12.

With the latest test I conducted mid last week for Jason I still used the 
large endpoint, because the server told me so.

Ciao
Stephan

**Comment by atvassilev** [comment]
Hmm, either the update has not made it to the public or something else. Let's see what the team says and will go from there.

**Comment by celic** [comment]
This is still in the implementation as of today but we are working on removing the endpoint altogether. We should prepare a branch of the protocol specification with this endpoint removed though while the server is made to match.

**Comment by smuellerDD** [comment]
Am Dienstag, 30. Juli 2019, 18:08:16 CEST schrieb Chris Celi:

Hi Chris,

> This is still in the implementation as of today but we are working on
> removing the endpoint altogether. We should prepare a branch of the
> protocol specification with this endpoint removed though while the server
> is made to match.

Let me know if you want me to test the regular endpoint with large data 
packets.

Ciao
Stephan

**Comment by celic** [comment]
Unfortunately this may be a bit down the road as we have some other features in the works. I'll keep everyone posted via the normal calls.

**Comment by Kritner** [comment]
Bumping this because we no longer require the use of the large endpoint.  

![image](https://user-images.githubusercontent.com/8814983/91051774-913ea380-e5ee-11ea-8583-1d3d8f1e679a.png)

The specification seems to already cover the fact that alternate handling *MAY* be needed, so I believe we should be safe to keep the current wording in there.  We might not be using that alternative handling, but that doesn't mean someone else implementing the protocol wouldn't.

Perhaps we can revisit at the next major revision of the spec?  With the current server implementation of the specification there'd not be an instance of a client receiving a change to their submission flow:

![image](https://user-images.githubusercontent.com/8814983/91052086-f7c3c180-e5ee-11ea-84ac-651dce04d6ab.png)

Removing the large endpoint information right now could *potentially* be a breaking change to clients, since the following properties would currently be expected to be received by the client from the server at the login endpoint:

![image](https://user-images.githubusercontent.com/8814983/91052226-293c8d00-e5ef-11ea-9052-b36585d5ac0b.png)

I'm going to close this for now, but feel free to re-open and comment if there are disagreements with my thinking.

**Comment by celic** [comment]
There was a version of the spec with the large endpoint removed.
Unfortunately it was made after the base documents were converted to
metanorma. This could be a future spec version topic though.
