### ISSUE TITLE
SHA : Failed to generate tests

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#688]
Is the SHA1, SHA2 registration in [SHA](https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-celi-acvp-sha-00.txt) still valid?
I tested with the format on it, and the demo system can create the test session but fail to generate tests.

**testSessionId**
19962

**vsId**
37142

**Algorithm registration**
   {
     "algorithm": "SHA2-256",
     "revision": "1.0",
     "messageLength": [0 , 65536]
   }

And while trying to download the vector set, it says:
{
    "vsId": 37142,
    "status": "error during vector generation",
    "message": "failed to generate tests for: 37142"
}

**Comment by Kritner** [comment]
@AndrewHYang did you intend for that to only allow 0 length and 65536 message lengths? I would imagine you'd want a range object for your math domain rather than two literals:

```json
{
	"messageLength": [{
		"min": 0,
		"max": 65536,
		"increment": 1
	}]
}
```

The specific reason for your failure is that the current MCT implementation relies on a message length matching the digest size, which would not be the case with your posted capabilities.

related #684

**Comment by celic** [comment]
@Kritner is correct here. The domain must contain the digest length as a value for the MCTs. The example in the SHA specification is correct.
