### ISSUE TITLE
domainSeed with leading 00 results inconsistent

### ISSUE THREAD

**Issue by bfussell** [usnistgov/ACVP#693]
After the fix for #664, I'm now seeing some instances where DSA tests(PQGGEN and PQGVER) fail when the domainSeed has the leading 00.  For example on demo server vsID 40907 tcId 94, server indicates verify passes, my client says it fails.  If i run the same data using the old CAVS test harness on openssl the verify fails. However, if I remove the leading 00 byte, the openssl test harness passes the verify.

I see similar issues on PQGGEN, vsId 40723, tcId 59

**Comment by celic** [comment]
Thanks for the specific tcIds. I'll take a look at this. It seems like the `domainSeed` has the proper length if you include the `"00"` byte. I'll look a bit deeper.

**Comment by celic** [comment]
vsId 40907, tcId 94 passes when run on our internal system as a GVer test. I think the issue here has to deal with how the hex is treated by the crypto. 

On our system, the `domainSeed` is treated as a `BigInteger` (or any other multi-precision integer, `BigInteger` is just the class of choice for our C#). When the hex is read in and converted to an integer, the leading `"00"` byte has no impact on the integer value. 

Looking more at the crypto, the `domainSeed` is concatenated together with some other values to form `U` (according to [A.2.4 in FIPS 186-4](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf)). When the `BigInteger` is passed back into a form for concatenation, the leading `"00"` is dropped. As `U` is then hashed to eventually form `g`, it makes sense that this causes a discrepancy between our implementations. I think this is a crypto error for the server.

The more I look at the specification, I think this is a crypto error by the server for this specific case. 186-4 is explicit in that `seedLen` must be greater to or equal to `N` (the length of `q`). If we remove the leading `"00"` byte when we perform the hashing for these tcIds, we do not satisfy this requirement on the server. 

It seems like your crypto implementation leaves the leading `"00"` byte there when concatenating to form `U` leading to a different `g` in the end, failing the verify, which is the correct response. This is a good catch. I'll get right on a fix.

**Comment by celic** [comment]
For my own notes... 

When `PQ` were generated using the `Probable` method, the `domainSeed` is just some arbitrary `N` or more bits. ACVP always chooses `N` bits. This should be the only place where a leading `00` could appear in a `domainSeed`.

When `PQ` were generated using the `Provable` method, the `firstSeed` must have a leading `1` bit and be `N` or more bits. ACVP again always chooses `N`, and satisfies both constraints. The `domainSeed` ends up being the concatenation of `firstSeed || pSeed || qSeed`. 

Some of this confusion might go away if we clean up how these values are communicated. Not sure if this was ever an issue for any of the existing clients.

**Comment by bfussell** [comment]
Thanks Chris !

**Comment by celic** [comment]
This has been pushed out to demo. Try a new registration and I guess hopefully it has a 00-byte to verify? Huh. Seems a little tricky to verify from an end user perspective. This did involve a crypto change on our end and all internal tests passed, including the spot test from the mentioned vector set.

**Comment by bfussell** [comment]
I've run DSA this morning and still see failures on PQGGen, but not on PQGVer(tbh I'm not sure if PQGVer was failing previously or not).

testSessions 25473
vsId 50920
tcId 51 and tcId 52

**Comment by celic** [comment]
I think I see the issue. I deployed the fix which was an update to our crypto. I just tested it again locally to be sure and everything is solid there. We utilize pools of domain parameters for some of these tests for speed and I think the bad values came from the pool. This is the first time we've had an issue like this that would affect some of our pre-computed values. Let me pull some values from our demo pool to be sure. I'll update you when I have something conclusive.

**Comment by celic** [comment]
Ok @bfussell it seems like we have identified the issue. I neglected to update our precomputed values for this crypto update. We are working on a fix and I'll let you know when to test again. You might not receive any test cases where the seed has one (or more) bytes of leading 0s as we are draining them from our pools, while trying to save the GBs of other good values.

**Comment by celic** [comment]
@bfussell faster than anticipated. Please test again. The crypto has been updated, but you will likely see no test cases that meet the mentioned condition until they naturally are refilled into our pool system with idle CPU time.

**Comment by bfussell** [comment]
Hmmm, may be some left.  However, it passed so maybe PQGVer doesn't have the issue ?  The result was failed so it's possible it was meant to fail for a reason other than thge domainSeed.

testSessions/29785/vectorSets/56148
    "tgId" : 14,
      "tcId" : 68,
      "p" : "A4FC159D48C77B632E0D5DF33BFD5012C772E833F1998FB80D828E076067508D51EBE502D24C2C883942A41E9B852A9CE3B259926408F30A3A2CCD5E0F57ECA94BCBE4AA346154DC93B35F9EE617B794E3413DB758B883D678AB604520BDCE596E46FF84F09CC0722FACD81CE2A80933915BF461081F193032F3619EB85F924180C911600C82C03C77105F0FA032184DB5BA9147BA0A153ED0796BF89D8BBA6EA7C5A1078CBA15480716294307D4F3A448C3DA692B866CD2B87C8BC8FCFD89383344DF46423D3B8BB35BEABA8F6CB8C29928C0F5D17CFEE2C6CB2C77AD7E7D56EA0D975ACC40BE27CA228388FCC550AAE61704FB058DB780E5B416AE498623B1",
      "q" : "9AB2FE0FFF66DEEE29320EFD620CEC1654DAB94C7B6486F295E54153",
      "g" : "661CE87150622724CA695025A830EAD8800A02A5A152DE7E1CC64B8F5DB458D104E6A23721F8429DBF7C6E105F58F44073F143575E903608540A6992FFE6A13979AF7D9C715ECAC3616136D75B328886584B75FEEDD18181821495ECBCA3FEF553C942E8DE4D8CE9F03128DF12B81CE9F62536FDDCF403BB985CE9FD48BAF48A41488F781C7FAC8F4852F3F08C19DE6B11DDA6B12E3F3DE3415E678ADCD53CE421B5F9F0242EC79CD6643D1AD84519FFE6C5D2849E163F3A39B4A6E31C82F4866CCB35A519C431E46245C76E7A7798E842830DD05BA8B0575B13B5561229E29ED3B891702D5B83F4962E2C4E6E9B4EEF0BB90DFE21C73EFD3C63019DB9C8128E",
      "domainSeed" : "00D4DC60F05FE89AD4BE8AF6D8EF66919B431A80CC2779F5FF8A79B3",
      "index" : "94"

**Comment by celic** [comment]
Both get their domain parameters from the same pool. Without looking too much into it, it is likely that this test case was supposed to mess up the seed and thus pulled a random value for the seed afterwards.

**Comment by bfussell** [comment]
K, sounds good. Will close and monitor
