### ISSUE TITLE
TDES test vectors with keying option 1 has all keys identical

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#696]
After getting a new TDES test vectors today with a request for keying option 1, I still get TDES test vectors with all keys being identical.

vsID: 41941 (tcID 101 and following)
vsID: 41942 (tcID 133 and following)

**Comment by celic** [comment]
I see why this is happening. I think this particular KAT was left off the update for some reason. I'll see about generating proper data for this. To be clear the only KATs with single keys will be CTR and OFB for `variablekey` testing. I think we normalize all the `testTypes` to `KAT`, but in terms of the client, there will be two groups (encrypt and decrypt) that have a single key rather than three distinct keys.

(Realized I never actually posted this yesterday... Thanks GitHub for saving my draft)

**Comment by celic** [comment]
We will have a fix for this for TDES-OFB and TDES-CTR in the next demo deployment.

**Comment by smuellerDD** [comment]
confirmed, working

**Comment by smuellerDD** [comment]
I need to reopen that issue. In a TDES CBC vector I get the following keys:

```
      "key1" : "1004801598190102",
      "key2" : "0101010101010101",
      "key3" : "1004801598190108",
```

My IUT rightfully flags this key as wrong due to the following: TDES keys only use the 56 MSB. The 8LSB are the integrity value. In the key above, only the integrity value is changed, but the actual key is identical.

Note my particular IUT performs a memcmp of the 56MSB of each key and not the full 64 bit. IMHO the IUT does the right thing.

**Comment by celic** [comment]
I interpreted the keys to be set up so the single LSB on each individual byte was the integrity value at which point the keys are distinct. I'll do some research here and see if the TDES specification provides an answer.

**Comment by celic** [comment]
This is from SP800-67r2, Appendix A, page 14-15.

>  One bit in each 8-bit byte of Key_i may be utilized for error detection in key generation, distribution and storage. Bits 8, 16, ..., 64 are used for assuring that each byte is of odd parity. (Note that these eight parity bits have no effect on the operation of the algorithm.)

**Comment by smuellerDD** [comment]
Of course - my bad and the IUT should be changed. Sorry for the noise.
