### ISSUE TITLE
General Registration Documentation Question: PayloadLength, IVLength and the like

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#706]
This question is related to registering algorithm capabilities and some fields within.  It is related to fields often related to length: *PayloadLen*, *aadLength*, *tagLen*, etc...

This question might be bred from in-experience in the world of FIPS and if this is the case I apologize for my ignorance.

I'm finding that it's difficult understand the structure that is expected when registering algorithms with particular fields.  I'll follow this up with examples - fair warning that this could become lengthy.

I believe this is more of a global issue with all the documentation but I'll pick and choose some examples to illustrate my point.

In all cases, I'm referring to the documentation found here:
https://usnistgov.github.io/ACVP/

The documentation for AES-GCM looks like the following:
![image](https://user-images.githubusercontent.com/3537360/65522957-8bf64780-deb9-11e9-8e9e-b4394f96c2bd.png)

It says that payload length is an object with a field for *min*, *max*, *inc*.
However, when I look at the example provided below, it is provided an array of integers:
![image](https://user-images.githubusercontent.com/3537360/65523180-e4c5e000-deb9-11e9-98fe-29089e7bd987.png)

**AES-CBC-CS2** describes payloadLength in a similar fashion:
![image](https://user-images.githubusercontent.com/3537360/65523459-4be39480-deba-11e9-8e76-ce7a5a00957f.png)

But the example describes that fields as an object:
![image](https://user-images.githubusercontent.com/3537360/65523398-37070100-deba-11e9-9fba-5deb1364156e.png)

There is also some confusion as to what the fields denote.  For example
![image](https://user-images.githubusercontent.com/3537360/65523852-dcba7000-deba-11e9-9f8f-1839b11c7a90.png)

This specifies s structure of:
```
{
    "min": 16,
    "max": 65536,
     "inc": any
}
```

Does **min** of 16 mean that the value for the field min has a minimum itself of 16, ie, [16-65536]
What does **inc** of **any** mean?  In some cases, the documentation table has inc as 0 and in this case it's any.  Does that mean something different?

There are also cases where the documentation specifies an object with that structure with a key of **inc** but the examples on the same page have the field as **increment**

**Comment by Kritner** [comment]
Hey @AlexThurston, I'll try to answer your questions/concerns:

> It says that payload length is an object with a field for min, max, inc.
> However, when I look at the example provided below, it is provided an array of integers:

From
https://usnistgov.github.io/ACVP/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.16.3

The type you're referencing are either of type `Range` or `Domain`, where their values can be represented in either object form (min,max,increment) or literal form (array of integers).

> Does min of 16 mean that the value for the field min has a minimum itself of 16, ie, [16-65536]

Correct 

> What does inc of any mean? In some cases, the documentation table has inc as 0 and in this case it's any. Does that mean something different?

I think the "any" was used to indicate any increment is valid (at long as the `max - min mod increment = 0`). 

> There are also cases where the documentation specifies an object with that structure with a key of inc but the examples on the same page have the field as increment.

I *believe* that the tables are more "loose" in that they can use abbreviations (like inc) and "any".  All the algorithms that actually make use of `Range`/`Domain` expect the full "increment" property, rather than "inc".  If you do happen to see otherwise somewhere, I'm guessing that's a mistake in the specification.

**Comment by AlexThurston** [comment]
@Kritner Very, very helpful.  The link is the piece that I was most certainly missing and must have glossed over.  Thanks very much.
