### ISSUE TITLE
Request list of dependency properties returns a 404

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#718]
**environment**
Both

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
GET https://acvts.nist.gov/acvp/v1/dependencies/properties

**Expected behaviour**
I seem to be getting a 404 from this route.  Issue https://github.com/usnistgov/ACVP/issues/671 was raised about this and was closed but it's unclear whether or not that route is supported.  It is described in the documentation here: https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.11.13.3 . If it is not, then the documentation should likely be updated. 

**Additional context**

**Comment by shaneshaffer** [comment]
Section 11.13 states:

> The possible name/value pairs for a given value of "type" MAY be provided by the response of Section 11.13.3, if the server implements this endpoint.  Otherwise a server MAY choose to restrict or not restrict the range of name/value pairs available, but any restrictions MUST be clearly documented.

At this point we are not restricting the name/value pairs available, and that endpoint is not supported. Personally it seems like it would be worthwhile to restrict the available pairs at some point in order to try to maintain some consistency and quality in the data, but we likely need to collect data for a while to determine what restrictions are reasonable. Of course, the longer we wait to impose such restrictions the more problems the restrictions are likely to cause.
