### ISSUE TITLE
Address publication: "region" not applicable to entire world

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#758]
When registering an address during publication, the ACVP server seemingly insists on having the "region" keyword filled (e.g. with the US state).

such region field, however, is not applicable to all parts of the world. For example, in Germany we do have states, but they are not relevant for any address.

Please make the field optional or allowing an empty string.

**Comment by shaneshaffer** [comment]
While I have not tested this to confirm, the code looks like it should allow for the region field to be omitted or have a null value, but if a value is supplied it can't be an empty string (and must otherwise conform to some other restrictions). Which of these cases (omitted/null/empty string) did you try?

**Comment by Kritner** [comment]
I just confirmed that the region portion of an address is not required when creating a vendor resource.
