### ISSUE TITLE
Updated one certificate for module 1, created new certificate for module 2

### ISSUE THREAD

**Issue by dsikkema-atsec** [usnistgov/ACVP#787]
**environment**
production

**testSessionId**
892 and 891

**vsId**
10681 and 10682  for testSession 892
10680 for testSession 891

**Algorithm registration**
892 - DRBG and SHA  updated on certificate A50
891 - SHA - new certificate A214, it could have been updated on A49

**Expected behavior**
The publication of testSession 891 was expected to give an update to certificate A49 instead of getting a new certificate. Or testSession 892 should have been a new certificate instead of updating A50

**Additional context**
I am not sure which would be more correct, updating both prior certificates, or getting 2 new certificates, but should be the same method for the testSessions.

**Comment by celic** [comment]
This was difficult to reply to originally because everything on that side of the project was in flux. Things are much more stable around the potential branches involved with updates. If this is still an issue or question, please let me know. I suspect so much has been updated on the server since then this may no longer be the case if you tried again.
