### ISSUE TITLE
Wait times on demo server questions

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#789]
Hello,

We have had some questions internally about the increase in wait times for generating vector sets in recent weeks. Ultimately, our client (libacvp) follows the spec in that it takes the "retry" value from the server and waits for that period of time before trying to get the vector set from a given URL again. However, the time currently remains constant at 30 seconds, and the wait times can be anywhere from a handful of seconds to over an hour for one set. Are there plans to dynamically adjust this retry value so that our users can have a better idea of how long it will take to get tests, or can any indication be made in the response message that the server is experiencing heavy load? Our client currently times out at 60 minutes waiting for a vector set, will this not be enough moving forward as more and more people use the demo server?

Thank you for your time!
Andrew

**Comment by smuellerDD** [comment]
Am Dienstag, 25. Februar 2020, 22:44:29 CET schrieb abkarcher:

Hi abkarcher,

> Hello,
> 
> We have had some questions internally about the increase in wait times for
> generating vector sets in recent weeks. Ultimately, our client (libacvp)
> follows the spec in that it takes the "retry" value from the server and
> waits for that period of time before trying to get the vector set from a
> given URL again. However, the time currently remains constant at 30
> seconds, and the wait times can be anywhere from a handful of seconds to
> over an hour for one set. Are there plans to dynamically adjust this retry
> value so that our users can have a better idea of how long it will take to
> get tests, or can any indication be made in the response message that the
> server is experiencing heavy load? Our client currently times out at 60
> minutes waiting for a vector set, will this not be enough moving forward as
> more and more people use the demo server?

I am not sure that such additional logic makes sense. The ACVP protocol 
specifies that after each retry a complete new HTTP session is created with a 
stand-alone request.

Thus, nothing prevents you from stimply connecting later than these 30 
seconds. In fact, that is what I use in my ACVP Proxy: a user can stop the 
ongoing waiting with the server and resume it at a later time. The ACVP server 
batches the generated vectors up for you to pick up. For example, when I start 
a request in the evening, stop all retry operations and come back next morning 
to obtain the vectors, I get the vectors within seconds.
> 
> Thank you for your time!
> Andrew



Ciao
Stephan

**Comment by jarnold01** [comment]
Hi Andrew,

Thanks for sharing your thoughts on the performance-related issues you've seen over the past month. 

To address the topic of performance from a high-level perspective, we are well aware of the decrease in overall performance, as we recently had to effectively re-baseline our performance-related configuration settings in both Demo and Prod due to some recent code changes (with further updates coming related to improving performance that we are presently testing internally.) 

Please know that we are actively working on continuing to tune both environments relative to available resources and usage. It's a delicate balance as I'm sure you can imagine. 

We definitely appreciate the feedback, and we hope that when the additional configuration changes and code updates are applied to Demo over the coming days and weeks, that overall performance will continue to increase as we work to reach that balance and an overall more efficient, stable and optimized state.

Thanks,
Jason

**Comment by abkarcher** [comment]
Thank you both for the detailed responses! We will work around it the best we can. In the future, it may be beneficial if the retry period was dynamically adjusted - otherwise, if users opt to retry again in our own time frame and deviate from the spec, should it exist within the spec at all?

**Comment by smuellerDD** [comment]
Am Donnerstag, 27. Februar 2020, 22:17:00 CET schrieb abkarcher:

Hi abkarcher,

> Thank you both for the detailed responses! We will work around it the best
> we can. In the future, it may be beneficial if the retry period was
> dynamically adjusted - otherwise, if users opt to retry again in our own
> time frame and deviate from the spec, should it exist within the spec at
> all?

I think it should exist as this allows a stateless client, i.e. the client 
just sends the request to the server and waits until it gets something back.

The solution where you come back at your own discretion requires the client to 
keep a state locally somehow to remember at least which test session ID and 
vsIDs were announced by the server.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Can we close this?
