### ISSUE TITLE
EDDSA Documentation

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#836]
**environment**
Doumentation

**testSessionId**
N/A

**vsId**
N/A

EDDSA documentation say that paload has a key which is an array of capabilities:
![image](https://user-images.githubusercontent.com/3537360/79773830-f19b9c80-82ff-11ea-8c74-e83e0dde54bc.png)

But the example doesn't not match this specification.
```json
{
		"algorithm": "EDDSA",
		"mode": "keyGen",
		"revision": "1.0",
		"prereqVals": [{
				"algorithm": "SHA",
				"valValue": "123456"
			},
			{
				"algorithm": "DRBG",
				"valValue": "123456"
			}
		],
		"curve": [
			"ED-25519",
			"ED-448"
		],
		"secretGenerationMode": [
			"extra bits",
			"testing candidates"
		]
}
```

I believe this is also true for the other mode of EDDSA.

Maybe this is related or in the same area as: https://github.com/usnistgov/ACVP/issues/512

**Comment by AlexThurston** [comment]
Out of curiosity, which is correct the example, or table's documentation?

**Comment by celic** [comment]
Almost always the example is the correct element. We grab those directly from our runs of ACVP.

**Comment by AlexThurston** [comment]
Not to be contradictory, but are you sure?

There are a number of places in examples throughout the documentation where the examples seem to be incorrect, or even invalid JSON.  In this particular case, if that were true, most of the other ED*** have a capabilities key that is an array and this would be the only one that doesn't.

I've been using the table's documentation and taking the examples with a grain of salt.

**Comment by celic** [comment]
For EDDSA right now, there is no capabilities array on any mode so in those cases both the table and examples are wrong. Every example is pulled directly from JSON we generate on our local instances. The specifications here all started with tables and little to no examples (or at least examples that weren't from our own JSON). When examples were added, sometimes the table wasn't updated which is why I said what I did. 

ED* is one of the few algorithms that wasn't a part of the original set of algorithms, so if definitely is an outlier.

**Comment by AlexThurston** [comment]
Understood.  As always, thanks for the clarification.

**Comment by celic** [comment]
As an aside, we are preparing new versions of all these documents. Not changing anything, just updating everything. Making sure these tables are accurate, examples are accurate, and certain, more programmatic sections exist. Also moving away from an XML format to an AsciiDoc format potentially to make it easier for others to contribute. The HTML and TXT output formats will stay though. I guess long story short, expect lots of these documentation issues to be fixed at once, hopefully sooner rather than later.

**Comment by AlexThurston** [comment]
Awesome @celic Thanks for that.
