### ISSUE TITLE
Update MCT Pseudocode to include IV in Inner Loop

### ISSUE THREAD

**Issue by celic** [usnistgov/ACVP#860]
The pseudocode currently implies the transition of the IV with no mention of it during the inner loop. This could be updated to

```
Key[0] = Key
IV[0] = IV
PT[0] = PT
For i = 0 to 99
    Output Key[i]
    Output IV[i]
    Output PT[0]
    For j = 0 to 999
        If ( j=0 )
            CT[j] = AES_CBC_CS_ENCRYPT(Key[i], IV[i], PT[j])
            PT[j+1] = IV[i] || MSB(CT, PT.length - IV.length)
        Else
            IV[j] = MSB(CT[j-1], IV.length)
            CT[j] = AES_CBC_CS_ENCRYPT(Key[i], IV[j] PT[j])
            PT[j+1] = CT[j-1]
    Output CT[j]
    AES_KEY_SHUFFLE(Key, CT)
    IV[i+1] = MSB(CT[j], IV.length)
    PT[0] = CT[j-1]
```

This would clarify where the IV is coming from during encryption.

**Comment by ardbiesheuvel** [comment]
I agree that the existing code is problematic, since it essentially defines AES_CBC_CS_ENCRYPT() as a stateful object that retains internal state in an unspecified way, rather than a function whose output is fully defined by its input values.

However, whether the above is correct depends on which flavor of ciphertext stealing has been implemented: Only CS1 puts the block that was encrypted last at the end of the output, and CS3 only does that if the input size is a round multiple of the block size. So for those cases, the above is accurate.

For the remaining cases, it is the penultimate full block of ciphertext, aligned to the block size. Since CS1 is rarely deployed, this pseudocode should probably cover CS2 and CS3, but separately.
