### ISSUE TITLE
DEMO: Creating Sample Vectors Sets and `infoGeneratedByServer` seem to have a relationship

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#875]
**environment**
DEMO

**testSessionId**
86562 (created as a sample vector set)
86572 (**NOT** created as sample)

**vsId**
219337
219381

**Algorithm registration**
```json
{
    "algorithm": "RSA",
    "mode": "keyGen",
    "revision": "1.0",
    "infoGeneratedByServer": false,
    "pubExpMode": "random",
    "keyFormat": "standard",
    "capabilities": [
        {
            "randPQ": "B.3.2",
            "properties": [
                {
                    "modulo": 2048,
                    "hashAlg": [
                        "SHA-1"
                    ]
                }
            ]
        }
    ]
}
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions/86572/vectorSets/{id} GET

**Expected behaviour**
This may apply in other places, but according to the examples for RSA Key Gen, if `infoGeneratedByServer` is set to `false`,  then the IUT will provide the values used.  And so, the vectors set test cases will contain something like like:
```json
{
      "tcId": 1,
      "deferred": true
}
```

However, if I create the test session as a **sample**, it seems as though the value I provide for `infoGeneratedByServer` is set to true because the vector set that is returned now has test cases that look as follows:
```json
{
      "tcId": 1,
      "seed": "B917FECE9570D96D844695250C4F287172653AA1303F3752B771813A",
      "e": "4F53DF45D52BCD"
}
``` 

**Additional context**
This could be related to the second part of the issue raised here: https://github.com/usnistgov/ACVP/issues/872

**Comment by celic** [comment]
Yes this is true. If this is a sample vector, the server assumes that it is responsible for generating all values regardless of any other property. This will be the same for any algorithm that utilizes the "Deferred" property. So even if the registration says the information will be generated by the client, the server will still perform some initial work. 

These two properties are closely related internally as they both trigger the work behind the scenes to generate an RSA key. 

It seems like the sample flag is getting in the way of the "infoGeneratedByServer" flag while writing out the JSON. Both will have a full RSA key available to them, but will have different properties shown in the prompt files.

**Comment by AlexThurston** [comment]
It does feel a bit jarring and misleading.  From a user's perspective, and maybe this is just a lack of understanding, the *sample* flag's purpose is to allow users the ability to generate a sometimes small subset of test groups and cases and give us access to what the expected answers are.  But in this case (and maybe others) it is actually changing what might have been registered as a capability.  I get that if you want the answers, then the server would have to generate its own values to be able to create answers, but rather than do that, I would just expect answers for this set of capabilities just to not be available.  To me, the test session and its vectors sets should behaved the same way whether it is a sample or not.

**Comment by celic** [comment]
It does not change what is registered. I might not have been clear, that likely is an error in which properties get written to the prompt/response files because `infoGeneratedByServer` and `isSample` are nearly identical behind the scenes.

The expected behavior for `infoGeneratedByServer = false` and `isSample = true` is that the server still generates all content needed for KeyGen, but only communicates the `deferred` state in the prompt (along with any other data available up front like the public key). The response file is then filled out with everything the client would send to the server, which in this case would be the completed key information.

I understand you want the response file to be empty here so that you as a client could provide this information. Technically speaking, the validation process ONLY pulls from the response file here, so you could submit a validation request using your own responses. This would be true for any deferred algorithm by the way. In this case we use the input information from the responses to verify they lead to the output information from the same file. 

This is not something we would look to change. IsSample is intended to have this interaction with deferred algorithms. The workaround _should_ be available but is not something we've tested or really intended to be available. It is just a by-product of how we set up deferred testing.

**Comment by AlexThurston** [comment]
Alright.  Thanks very much for the explanation - I think that all makes sense.  But just to confirm things one more time so it's clear to me.  If I create a test session as a sample where **infoGeneratedByServer** is false, and in my response provide values for the test case that are different than the ones that were generated by the server because of the fact that it was a sample, the responses I provide will still validate.  Would that be a true statement?

**Comment by celic** [comment]
I haven't tried it personally, but I believe it should validate. Just make sure you follow the test group properties.

**Comment by AlexThurston** [comment]
Wonderful.  I'll mark this as closed and if it crops up again, we can revisit.  Thanks for the explanation.

**Comment by celic** [comment]
The background information is that on deferred cases we pull various pieces of information from the prompt and responses in order to run the crypto operation ourselves regardless of if the vector set was a sample or not. 

So even though we provide answers, it is easy to see they aren't the only possible answers. That workflow is just not super transparent, and I'll be honest, I didn't realize it was available until this conversation.

**Comment by AlexThurston** [comment]
Well it makes me feel less bad about having you spend time on this if we both learned something ;)

Leave up to users of your system to bring up questions you didn't even know would exist...  
A million monkeys with typewriters will write Shakespeare eventually...as they say.

As always, thanks for time and help.
