### ISSUE TITLE
empty approvedUrl for validation request, or stuck in initial

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP#876]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
Empty approvedUrl: /acvp/v1/requests/13079
Stuck in initial (or longer than usual): /acvp/v1/requests/13080

**Expected behavior**
Usually, our validation requests are approved quickly/automatically on Demo. However, some have been approved with empty approvedUrl (These may have been resubmissions of already approved algorithms, unsure at this time) or are stuck initial (Perhaps new systems handle it differently?)

Thanks,
Andrew

**Comment by Kritner** [comment]
@abkarcher I *believe* the approvedUrl was removed for certified test sessions because in all other "request types" the approvedUrl actually led to a resource; in the certifies case it did not.  No endpoint existed for the approvedUrl that was previously returned for test sessions.

This particular removal of the approvedUrl was intentional, but let me know if you've seen anything else exhibiting that behavior.

Regarding your two test session certify requests that are stuck, we'll look into it, thanks!
