### ISSUE TITLE
sample test vector from FF1 draft

### ISSUE THREAD

**Issue by surajshardade** [usnistgov/ACVP#909]
Hi,

When I went through a draft for the AES-FF1 algorithm, I found 2 sample test vectors and their expected ciphertext. I just wanted to know , Is the provided CT are actual CT for Plain Text given or just sample to represent how the request and response look like when accessing the Demo server and not having any relation to plain text given?

Thanks.

![ACVP_TEST_VECTOR](https://user-images.githubusercontent.com/43987488/85385961-99338600-b560-11ea-889d-718f23ae59cc.PNG)

![ACVP_TEST_RESPONSE](https://user-images.githubusercontent.com/43987488/85386070-be27f900-b560-11ea-9321-96362e974684.PNG)

**Comment by Kritner** [comment]
The above sample posted the first one does seem to be valid, but the second one not.  I'm not sure if writing out the sample if i perhaps transposed the ct from another test case I was playing with internally, or if i truncated it and failed to write an ellipses like the sample json for other algorithms in the same document. 

You (generally speaking) can't rely on the sample cases in these documents as being valid, they're intended more for structure rather than being "valid test cases from the crypto" AFAIK.

**Comment by Kritner** [comment]
FWIW starting in this comment: https://github.com/usnistgov/ACVP/issues/681#issuecomment-516397570 and ending in this comment: https://github.com/usnistgov/ACVP/issues/681#issuecomment-516668397 should give at least one sample test case and intermediate values throughout the various rounds of the crypto.

**Comment by celic** [comment]
If you need examples to test an implementation, use the `isSample: true` flag during the registration. This makes it so that the `/testSessions/{id}/vectorSets/{vsID}/expectedResults` endpoint is available to grab the expected responses. The specifications might truncate some of the JSON values to fit within the bounds of the page, or could be from different runs of the same algorithm.

**Comment by surajshardade** [comment]
OK. got it.
Thanks a lot, Russ and Chris. :)
