### ISSUE TITLE
GET /oes/<id> differences

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#911]
This is a note about a difference compared to the previous web frontend. I can live with either implementation. Thus, it is an FYI for you to decide whether something needs to be done.

GET /oes/<id> used to return the keyword "dependencies" with an array of the fully exploded dependency listing. Now, it contains "dependencyUrls" which is an array of URLs where the client needs to perform a GET on each URL to get the dependencies.

**Comment by Kritner** [comment]
Hey @smuellerDD I don't know where it came up previously, and the title and body of this issue seem to imply separate endpoints.  Just to confirm, you're concerned about the OES listing, not `/oes/{id}` correct?  I know we had an issue out there around the `/oes/{id}`, and just confirmed that that endpoint is returning the hydrated `dependencies`, rather than `dependencyUrls`.  

There is also #638 out there, that I'm treating as just a specification update at this point, we implemented this particular set of endpoints to the spec, not what was out there in the old stack.

All that being said, that OES listing endpoint can be updated to return the full dependencies.  I'll try to get to this change in the next few days (or another dev can) if there are no objections from other clients/devs @shaneshaffer @celic @bfussell

**Comment by smuellerDD** [comment]
Am Freitag, 26. Juni 2020, 11:11:57 CEST schrieb Russ Hammett:

Hi Russ,

> Hey @smuellerDD I don't know where it came up previously, and the title and
> body of this issue seem to imply separate endpoints.  Just to confirm,
> you're concerned about the OES listing, not `/oes/{id}` correct?

I am reporting the data returned by the server from GET /oes/{id}.

> I know we
> had an issue out there around the `/oes/{id}`, and just confirmed that that
> endpoint is returning the hydrated `dependencies`, rather than
> `dependencyUrls`.

In the past it returned `dependencies` which contained the full JSON structure 
with all information of that dependency. Now, the server returns 
`dependencyUrls` with the URLs that the client must separately query with a 
GET operation to obtain the dependency details.

> 
> There is also #638 out there, that I'm treating as just a specification
> update at this point, we implemented this particular set of endpoints to
> the spec, not what was out there in the old stack.

You are right that #638 reports the same thing. But before the web frontend 
transition, the server indeed returned `dependecies`. But after the transition 
is now returns only `dependencyUrls` again which implies that the issue #638 
is now open again.
> 
> All that being said, that OES listing endpoint can be updated to return the
> full dependencies.  I'll try to get to this change in the next few days (or
> another dev can) if there are no objections from other clients/devs
> @shaneshaffer @celic @bfussell


Ciao
Stephan

**Comment by Kritner** [comment]
Can you share the full URL you're attempting and which environment? I can only hit demo myself, but I'm seeing full dependencies returned from `/oes/{id}`:

![image](https://user-images.githubusercontent.com/8814983/85857514-037a3f80-b788-11ea-86ae-cb61f98fb342.png)

**Comment by smuellerDD** [comment]
Bummer - when I retried it, I get `dependencies` as you do.

But I had to implement the `dependencyUrls`  handler last night to get the register 12001 on the prod server

**Comment by smuellerDD** [comment]
Let me close the issue as I do not see the problem any more...

**Comment by Kritner** [comment]
I don't know enough about how your client operates, but is it possible it was pulling a cached view of that OE from your client's internal database?  I know at one point since deploying the new code and now we *were* returning the "depenendyUrls" rather than "dependencies" from the `/oes/{id}` endpoint, but that has been corrected for some time now.

FWIW here's when that change went into our codebase, it probably would have been on demo/prod within a few days of that:

![image](https://user-images.githubusercontent.com/8814983/85862379-ae422c00-b78f-11ea-9e5a-2868aab8c2c5.png)

**Comment by smuellerDD** [comment]
Am Freitag, 26. Juni 2020, 15:30:59 CEST schrieb Russ Hammett:

Hi Russ,

> I don't know enough about how your client operates, but is it possible it
> was pulling a cached view of that OE from your client's internal database? 

This is not possible because the data stored locally in a very different 
format that complies with the internal data structures I use. There is 
certainly no JSON structure with `dependencies` or `dependencyUrls`.

Note, my client only pulls this meta data from the server during publication 
to ensure the local and server data are in sync. And during that check, I have 
a matching logic for each type of meta data comparing the local and remote 
data. Only if both sides are in sync, my client proceeds with a publication 
request. If there is a deviation it allows the user to either create a new 
entry, or update an existing one.

> I know at one point since deploying the new code and now we *were*
> returning the "depenendyUrls" rather than "dependencies" from the
> `/oes/{id}` endpoint, but that has been corrected for some time now.

Note, I was hitting the prod server last night. And I received a 
dependencyUrls from the server.
> 
> FWIW here's when that change went into our codebase, it probably would have
> been on demo/prod within a few days of that:
> 
> ![image](https://user-images.githubusercontent.com/8814983/85862379-ae422c00
> -b78f-11ea-9e5a-2868aab8c2c5.png)


Ciao
Stephan

**Comment by Kritner** [comment]
Hmm... then I'm at a bit of a loss.  the endpoint `/oes/`, `/oes/{query}` both return "dependencyUrls", but `/oes/{id}` endpoint has been returning "dependencies" for several weeks now.

**Comment by smuellerDD** [comment]
Am Freitag, 26. Juni 2020, 15:44:07 CEST schrieb Russ Hammett:

Hi Russ,

> Hmm... then I'm at a bit of a loss.  the endpoint `/oes/`, `/oes/{query}`
> both return "dependencyUrls", but `/oes/{id}` endpoint has been returning
> "dependencies" for several weeks now.

Ahh, that seems to be it - I checked what I did last night (it was late and I 
seem to have not memorized all). I had no local OE ID last night. This causes 
my client to perform a search query at /oes and analyze the return data to 
identify whether the OE was already on the server to use its ID. So, I think I 
see what you outline.

What I saw this morning was a test where I had an OE ID. In this case, my 
client goes straight to /oes/{id}.

I have this logic structure in my client for a long time and it did not 
change. As I had never to parse `dependencyUrls` the response from the server 
for my /oes{query} is different than it was before.

Ciao
Stephan

**Comment by Kritner** [comment]
We can certainly return `dependencies` rather than `dependencyUrls` from the OES listing endpoint, similar to how `oes/{id}` does, I don't know how that would impact other people's clients however.  

This is a pretty unfortunate situation, in that this differs from the *old* code, but it abides to the spec, which the old code did not.

**Comment by smuellerDD** [comment]
Am Freitag, 26. Juni 2020, 16:20:51 CEST schrieb Russ Hammett:

Hi Russ,

> We can certainly return `dependencies` rather than `dependencyUrls` from the
> OES listing endpoint, similar to how `oes/{id}` does, I don't know how that
> would impact other people's clients however.
> 
> This is a pretty unfortunate situation, in that this differs from the *old*
> code, but it abides to the spec, which the old code did not.

Again, I am totally fine either way - my client can now handle both scenarios 
as it searches for both `dependencies` and `dependencyUrls` and takes what it 
finds for any request.

As this was a report for your information, you decide what to do. :-)

Ciao
Stephan
