### ISSUE TITLE
acvp-proxy error message when trying to verify test vectors

### ISSUE THREAD

**Issue by davecornwell** [usnistgov/ACVP#931]
**environment**
PROD

**testSessionId**
1906

**vsId**
21494 and 21495

**Endpoint in which the error is experienced**
ACVPProxy POST error 403

**Expected behavior**
I expected the testvector-response.json vectors to be verified

**Additional context**
ACVPProxy (17:26:37) (vid21495) Warning - HTTP operation: Unable to HTTP POST data for URL https://acvts.nist.gov:443/acvp/v1/testSessions/1906/vectorSets/21495/results: 403
ACVPProxy (17:26:37) (vid21495) Error: Failure to submit testID 1906 with vsID 21495
ACVPProxy (17:26:38) (vid21494) Warning - HTTP operation: Unable to HTTP POST data for URL https://acvts.nist.gov:443/acvp/v1/testSessions/1906/vectorSets/21494/results: 403
ACVPProxy (17:26:38) (vid21494) Error: Failure to submit testID 1906 with vsID 21494
ACVPProxy (17:26:38) (tid1906) Warning: Not all test verdicts obtained for testID 1906 (2 missing) - use options --testid 1906 to retry fetching them
ACVPProxy (17:26:38) (acvp-proxy) Warning: At least one thread returned an error: -111

**Comment by Kritner** [comment]
You need to ensure the JWT you're using is the one received as a result of the registration process, not the one upon initial login.  If you decode the JWT you should see the claims to your test session, the one you attempted to post results with had no claims; it was most likely just a login JWT, rather than a test session JWT.

If assistance is needed in operating the ACVP Proxy, an issue should probably be opened there: https://github.com/smuellerDD/acvpproxy/issues

tagging @smuellerDD for visibility

**Comment by jarnold01** [comment]
We think this is related to issue #929 as all looks as expected on the server side. Closing this out.
