### ISSUE TITLE
Suggestions: Accept a DELETE <testsession> before processing

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP#932]
Currently, when calling:

```
DELETE /acvp/v1/testSessions/98947 HTTP/1.1
```

before the server processes the test session, one gets back:

```
{
  "error":"Validation error(s) on JSON payload.",
  "context":[
    "testSession does not exist or has not yet begun processing."
  ]
}
```

IMHO that does not make sense because if one erroneously registered a test session why not allowing him to delete it before processing started to avoid wasting server resources?

Note, my client automatically deletes ongoing registrations if it received a SIGINT to avoid having stale test sessions around.

**Comment by celic** [comment]
When you register a test session it doesn't immediately exist on our system. We first create all the necessary IDs for the test session on the external platform and communicate them to the internal platform (MessageQueueProcessor). From there the test session and vector sets are created. If you try to DELETE a test session before this happens, this is the error you can expect. We don't have a way around this on our end. We cannot create the data types from the external WebPublic. The most we could do is, if this error is returned, look at the MessageQueue for the related message and remove it but that has its own issues. 

At most you would need to wait a few seconds for the test session to be created fully before deleting it. 

It's a consequence of the architecture we need. All data must go to the internal system in order to process anything.

**Comment by smuellerDD** [comment]
Thanks for the explanation
