### ISSUE TITLE
KAS ECC Fixed String Derivation

### ISSUE THREAD

**Issue by mpirretti** [usnistgov/ACVP#941]
In the past with CAVS testing the validation lab was able to provide helpful debug information in the form of the .fax files and additional logs indicating where algorithms may be failing. Also, the CMVP hosted several of these example .fax files such as here (https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/keymgmt/KASTestVectorsECC2014.zip). Notably these vectors provide several critical intermediate values (such as the shared secret, or the fixed string in hex) to aid in debugging implementation issues. For a complicated, multi-part algorithm such as KAS ECC OnePass with hash based onestep KDF this debugging information is critical. 

We are unable to progress on our algorithm testing. For example we are unable to reproduce the dkm in the below JSON validity test where we know the expected result is that the test should pass. For us our interpretation is that we should obtain the following intermediate values for shared secret and the fixed string. Can you confirm this?
shared secret = 0791b6a73f89c54cd17060b69c221d7a93afdba2159cb2c90bff315d251f8eb94488a9a1694af35329eb5ded47ba5f08
literal_encoding = 30313233343536373839616263646566
fixed-str (used || to better illuminate where the substrings are, the actual string is a hex string without these symbols) = 1234567890ABCDEF||434156536964||30313233343536373839616263646566

```json
[
  {
    "acvVersion": "1.0"
  },
  {
    "vsId": 272937,
    "algorithm": "KAS-ECC",
    "revision": "Sp800-56Ar3",
    "isSample": true,
    "testGroups": [
      {
        "tgId": 5,
        "testType": "VAL",
        "tests": [
          {
            "staticPublicServerX": "C49465F3D4BE01AE61CCE33B5FC90EA149F5EE5633F27FB2EA10AF37A501CD86",
            "staticPublicServerY": "D5EA3D0BFF466966E91998CE0A87DC4FF00645485097A57EBCA79FF29307D20E",
            "ephemeralPrivateIut": "833BDABC61DF6C74D4EF395C873A2CFB0E477D9C84B87AA1622CB1A706DF9215",
            "ephemeralPublicIutX": "4466E4A40CE4B46B71CD59673314E9B0599091564A0275BD0858076337D333BA",
            "ephemeralPublicIutY": "2BECD9E56AB935CE439E3B2CD2BD5BBC7BEA3143C985A7340946C8993C6839DB",
            "tcId": 41,
            "kdfParameter": {
              "kdfType": "oneStep"
            },
            "dkm": "8C3114684B16E5D125EA0F83AE6D99C7ED26E01B13672D80C596409A1478852A4FE5F5D7CA096303FDD9A082E7B5D42CD9989ED8272217CCCB400EE9018272D47F65F809166436591E627D365407E8855342114B10BE0F6A3604319A6FEACC91A0BE5F6A1715BD08047ED8ABEA8FA3E6BD63E0468EBEA6FE6B8EA21C1A5B43C8"
          },
    ]
  }
]
```

**Comment by Kritner** [comment]
From your registration as well as the test group, the fixed info pattern was:

```
"fixedInfoPattern":"uPartyInfo||vPartyInfo||literal[0123456789abcdef]"
```

where from https://github.com/usnistgov/ACVP/issues/941#issue-674352990 it was stated:

```
1234567890ABCDEF||434156536964||30313233343536373839616263646566
```

Where is the `literal_string` "30313233343536373839616263646566" coming from? The `iutId` is `1234567890ABCDEF`, the server id is `434156536964` which accounts for the first two "blocks", but I'm not sure what's making up the "30313233343536373839616263646566", as that should be the literal "0123456789abcdef" as specified by `literal[0123456789abcdef]` in the fixed info pattern.

As far as your shared secret `z`, we have a different shared secret `z` for this particular test case, though the one you specified `0791b6a73f89c54cd17060b69c221d7a93afdba2159cb2c90bff315d251f8eb94488a9a1694af35329eb5ded47ba5f08` does actually occur in this test session, specifically tcId 116, rather than tcId 41 https://github.com/usnistgov/ACVP/issues/941#issue-674352990.  The `z` we calculated for tcId 41 was: `921F569CDB2381E19A0AB757D55C3B499413BC83E496A31C7C5209B7601CD3FB`

Is this perhaps a matter of copy/pasting from the wrong tcId?  I can take a look on our end if not.

As far as intermediate values with KAS, yes KAS is definitely a complex algorithm for testing. We have started putting together Shared Secret Computation testing (which I see you have registered for within this same test session), and there is also KDF specific testing being introduced.  The KDF specific testing is available on demo, and the specification should be available on this repo shortly (but you can take a look [here](https://celic.github.io/acvp-metanorma/draft-gold-acvp-sub-kas-kdf-onestep-Sp800-56Cr1.html) in the meantime).

**Comment by mpirretti** [comment]
Ah yes, this was a copy paste issue. I did mean to paste the contents of tcId116:

        "tests": [
          {
            "ephemeralPublicServerX": "12AD7CE2A59268153E79ECC8234577073F2EFC99EDE450CFFD910318C8FD368EA128548659956CFE4BAFF46EAA4687DC",
            "ephemeralPublicServerY": "756B19DF266BDEB5112E3C5916C2BEA1CDC62EACADD47151BF2419582FB6D9CCAB132B72A92C946AF39F28DFADF14D77",
            "staticPrivateIut": "9BC987D110653608CFDAD2E42CA8D70C82065628262BBEA57790B2736A9E08595D8ABA1702578BC97B13147DDD06FBF2",
            "staticPublicIutX": "C229BA54D0831CFA6956B4BC0AAA1F45E657B3EB89F452110D6C6A36290262899325AF0E1B55BBD3F80D9404E0EACB6D",
            "staticPublicIutY": "94CC09EDB22CF0C8C43335CC5C722C3EB1BA303103864F62257A272C471E0BC225215255DBD8074138078D2DD663040B",
            "tcId": 116,
            "kdfParameter": {
              "kdfType": "oneStep"
            },
            "dkm": "80B1AEFD67CB13881256C823086C0041565FBD4D8D5728015A3EA39AE0F199B061C30F2C77C639C01553C233BA85EF8E1EAE175237C69D26F12464AFDDAB0DED64FF9F9F399CE3DBB680D65BC1C0752ABA4E33E587FEF1129EAAF3E7E30FBC21A500AAF7732EB52CACDEB3F2113260D805D873DBB4CAAD162EBCF6F8D43413D5"
          },

The endcoding of the literal we did was based on the assumption it was a ASCII string, so encoded as hex that would be `30313233343536373839616263646566`. We did try various permutations of encodings, and ordering. So then the correct fixed string here should be (server's ID would go first since IUT is the responder in this tcid)?: `434156536964||1234567890ABCDEF||0123456789abcdef`

And from that the actual data being hashed in the first iteration of the KDF (SHA-384) would be:
`00000001||0791b6a73f89c54cd17060b69c221d7a93afdba2159cb2c90bff315d251f8eb94488a9a1694af35329eb5ded47ba5f08||434156536964||1234567890ABCDEF||0123456789abcdef`

**Comment by Kritner** [comment]
Ah, yeah the values between `literal[` and `]` are expected to be hex, and are plopped in just as registered.

I don't have the intermediate values in regards to the KDF handy (I can probably grab them tomorrow) - but assuming the correction was done for the `literal` portion of the fixed into, you can do a `PUT` rather than `POST` at the endpoint where your responses are submitted (at least on demo) to "try again".  Seems that we agreed up to the shared secret of Z, so hopefully with the fixed info correction it will be good to go.

If not, I can take a look in the morning.

**Comment by mpirretti** [comment]
Yes, please have a look at the KDF intermediate values on your end. We are not matching the expected results file which is getting:
`80B1AEFD67CB13881256C823086C0041565FBD4D8D5728015A3EA39AE0F199B061C30F2C77C639C01553C233BA85EF8E1EAE175237C69D26F12464AFDDAB0DED64FF9F9F399CE3DBB680D65BC1C0752ABA4E33E587FEF1129EAAF3E7E30FBC21A500AAF7732EB52CACDEB3F2113260D805D873DBB4CAAD162EBCF6F8D43413D5`

**Comment by Kritner** [comment]
Ah I believe I see the issue, and perhaps it's just not clear enough in the github specification.

your initial message to hash:

```
00000001||
0791b6a73f89c54cd17060b69c221d7a93afdba2159cb2c90bff315d251f8eb94488a9a1694af35329eb5ded47ba5f08||
434156536964||
1234567890ABCDEF||
0123456789abcdef
```

our initial message to hash:

```
00000001||
0791B6A73F89C54CD17060B69C221D7A93AFDBA2159CB2C90BFF315D251F8EB94488A9A1694AF35329EB5DED47BA5F08||
434156536964||
12AD7CE2A59268153E79ECC8234577073F2EFC99EDE450CFFD910318C8FD368EA128548659956CFE4BAFF46EAA4687DC||
756B19DF266BDEB5112E3C5916C2BEA1CDC62EACADD47151BF2419582FB6D9CCAB132B72A92C946AF39F28DFADF14D77||
1234567890ABCDEF||
0123456789ABCDEF
```
the difference being the ephemeral public key being provided as a part of the party info:

```
12AD7CE2A59268153E79ECC8234577073F2EFC99EDE450CFFD910318C8FD368EA128548659956CFE4BAFF46EAA4687DC||
756B19DF266BDEB5112E3C5916C2BEA1CDC62EACADD47151BF2419582FB6D9CCAB132B72A92C946AF39F28DFADF14D77||
```

Perhaps it was made as an assumption that the ephemeral data (be it via ephemeral key, nonce, or dkm nonce) would always be a part of its respective party[x]Info (I highlighted party U, but it's pertinent to both parties):

![image](https://user-images.githubusercontent.com/8814983/89658213-40177b80-d89c-11ea-8874-9ff62e028bd4.png)

The above does not explicitly state only *ephemeral* data goes in this field (as opposed to static), but since it's specifically called out that a nonce can be used in static schemes, that seems to make the most sense (at least to me).  It additionally does not say including the key information is required, but we have been using it at least as a part of our testing.

I believe it makes sense to continue including only the ephemeral data *at least as it relates to testing w/ acvp*, but probably best to get some other opinions as well (and if it changes we'll need to consider how that would impact current registrations and future registrations that would need to distinguish what exactly is included as a part of `party[X]Info`)

Thoughts @hallnist, @celic, others?

**Comment by mpirretti** [comment]
Ah, yes that would explain it. We certainly did not include the ephemeral key info in the fixed string. 

I would argue that the ephemeral keys are not strictly required to be explicit fields in the fixed string as they are implicitly included (ie both parties would derive different shared secrets if an incorrect ephemeral public key was used by either party). Perhaps it could be an optional field. 

In any case, I think the documentation should be updated to make this more clear. This is what is currently defined  
[here](https://github.com/usnistgov/ACVP/blob/master/artifacts/acvp_sub_kas_ecc_Sp800-56Ar3.txt):

    uPartyInfo
        uPartyId { || dkmNonce } { || c }
    vPartyInfo
        vPartyId { || dkmNonce } { || c }
To me this implies the `[u,v]PartyId` is the only required field of `[u,v]PartyInfo`. Also, I don't find anwhere where `c` is defined.

**Comment by Kritner** [comment]
Yes the documentation should definitely be updated.  I plan on expanding:

```
uPartyInfo
    uPartyId { || dkmNonce } { || c }
vPartyInfo
    vPartyId { || dkmNonce } { || c }
```

to instead be:

```
uPartyInfo
    uPartyId { || uPartyEphemeralKey } { || uPartyEphemeralNonce } { || uPartyDkmNonce } { || c }
vPartyInfo
    uPartyId { || uPartyEphemeralKey } { || uPartyEphemeralNonce } { || uPartyDkmNonce } { || c }
```

`{ || c }` is from the IFC perspective, the sections are shared between the different KAS flavors.

**Comment by mpirretti** [comment]
Thanks for clarifying.

**Comment by Kritner** [comment]
The documentation update has been moved to this repo, @mpirretti were you able to get things working after including the ephemeral in the fixed info?  I'll close this for now, but feel free to reopen and/or comment if something needs addressing related to this issue.
