### ISSUE TITLE
'404 Not Found' for SHA1/2 Testsession

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP#981]
**environment**
Demo

**testSessionId**
/acvp/v1/testSessions/103313

**Algorithm registration**
`{
    "algorithms": [
        {
            "messageLength": [
                160,
                {
                    "min": 1024,
                    "max": 65536,
                    "increment": 1
                }
            ],
            "algorithm": "SHA-1",
            "revision": "1.0"
        },
        {
            "messageLength": [
                224,
                {
                    "min": 1024,
                    "max": 65536,
                    "increment": 1
                }
            ],
            "algorithm": "SHA2-224",
            "revision": "1.0"
        },
        {
            "messageLength": [
                256,
                {
                    "min": 1024,
                    "max": 65536,
                    "increment": 1
                }
            ],
            "algorithm": "SHA2-256",
            "revision": "1.0"
        },
        {
            "messageLength": [
                384,
                {
                    "min": 1024,
                    "max": 65536,
                    "increment": 1
                }
            ],
            "algorithm": "SHA2-384",
            "revision": "1.0"
        },
        {
            "messageLength": [
                512,
                {
                    "min": 1024,
                    "max": 65536,
                    "increment": 1
                }
            ],
            "algorithm": "SHA2-512",
            "revision": "1.0"
        },
        {
            "messageLength": [
                224,
                {
                    "min": 1024,
                    "max": 65536,
                    "increment": 1
                }
            ],
            "algorithm": "SHA2-512/224",
            "revision": "1.0"
        },
        {
            "messageLength": [
                256,
                {
                    "min": 1024,
                    "max": 65536,
                    "increment": 1
                }
            ],
            "algorithm": "SHA2-512/256",
            "revision": "1.0"
        }
    ],
    "encryptAtRest": false,
    "isSample": true
}`

**Endpoint in which the error is experienced**
`{
"type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",  
"title": "Not Found",
"status": 404,
"traceId": "|da33d8e5-43f8773cc3d3cab0."
}`

**Comment by Kritner** [comment]
@AndrewHYang just to confirm - I don't see any 404s in our logs related to the endpoint `/acvp/v1/testSessions/103313` but I do see a few 404s at the endpoint: `/acvp/v1/testSessions/103313/results`.  The `/acvp/v1/testSessions/103313/results` endpoint isn't mentioned in the issue so I wanted to confirm we're on the same page.

There is a several minute difference I'm seeing when trying to hit the endpoint that was returning 404s, so that is a bit strange, I'll take a look into it.  

It looks like this test session has completely generated vectors at this point, are you able to confirm that the `/acvp/v1/testSessions/103313/results` endpoint is returning data now?

**Comment by AndrewHYang** [comment]
@Kritner sorry I'm not 100% sure, because I did not keep the logs. But /acvp/v1/testSessions/103313/results was also in the chain of requests, so it's likely where the error is from.
Also yes, /acvp/v1/testSessions/103313/results endpoint is working fine now. Does it mean the test session was not generated completely before?

**Comment by Kritner** [comment]
> Does it mean the test session was not generated completely before?

We had some intermittent connectivity issues around the time of this vector set, everything does seem to be cleared up, but feel free to bump if it's noticed again.  The test session was fully generated but that fact was not being communicated back to you properly.

Generally speaking the two endpoints you hit `/testSessions/{id}` and `/testSessions/{id}/results` should be responsive within ~30 seconds of POSTing to `/testSessions`, but because of the aforementioned connectivity issue some internal processes were being held up.
