### ISSUE TITLE
QUESTION: Production access requirements

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#989]
Does access to the production ACVP server still require ISO 17025 certification?  It was my understanding that it did a while back, but this (https://github.com/usnistgov/ACVP/wiki/ACVTS-End-User-Documentation#how-to-gain-access-to-acvts) seems to suggest that this isn't the case.

As another observation, is that document accurate?  I noticed that it makes reference to an *organization* and an *implementation* but I believe in most other places (like the API) it's called *vendor* and *module*.

**Comment by celic** [comment]
We call them vendor and module internally but kept the organization and implementation externally. @rstaplesnist can you update the wiki?

**Comment by AlexThurston** [comment]
Cool.  What about the first question about requirements on ACVP production access?

**Comment by celic** [comment]
NVLAP accreditation is a requirement for access to the Production ACVP environment. We modified the requirements slightly while starting ACVP to allow for first-party labs to participate in the CAVP. As I understand, this modification is still in progress via NIST Handbook 150-7. Any participants in the Production ACVP server were told they must be working towards this requirement.

After double checking with Tim, the requirements had a deadline during the Winter/Spring but that was relaxed due to external factors. Part of that is because an element of the accreditation process was an on-site visit which is not always possible at the moment. 

We will update the wiki with this information when we get a chance.

**Comment by AlexThurston** [comment]
Perfect.  Thanks very much for the clarification.

**Comment by rstaplesnist** [comment]
> We call them vendor and module internally but kept the organization and implementation externally. @rstaplesnist can you update the wiki?

Just looked through it and only found those in one location.  Looks like just a mental slip on my part.  Like Chris said, we use different terms internally for some parts of the data model.

No problem, I fixed the incorrect wording.
