### ISSUE TITLE
In Symmetric sub-spec why not range for AES-GCM AAD?

### ISSUE THREAD

**Issue by hbooth** [usnistgov/ACVP#99]
Was there a reason why in section 2.3 of the Symmetric sub-spec that the AES-GCM AAD is not also range?

I would think range is fine across the board.

**Comment by Kritner** [comment]
This was related to a conversation we had during a stand up, since it's asking for (up to) 5 values, with differing modulus requirements, it would not necessarily make sense as a range.  

`0, 128, 130, 147, 256` would be valid values to provide for such an AAD array - it would be difficult to represent that as a range no?

**Comment by atvassilev** [comment]
I believe this question/issue is resolved.
